### ISSUE TITLE
Оплата по безналу

### ISSUE THREAD

**Issue by IamWinWon** [shtrih-m/javapos_shtrih#107]
В свойствах описано:
Наименования типов оплаты
Расширенная оплата 9 - Расширенной оплатой (это безнал?)
Так же мир/виза/мастеркард - делятся разными методами summ(2,3,4).
Возможно как-то обрабатывать вызовы со всех карт одним методом?

**Comment by IamWinWon** [comment]
В общем для таких как я:
sum2 - mir
sum3 - visa
sum4 - mastercard
Общего нет.

**Comment by nyxiscoo1** [comment]
Sum2, Sum3 если мне не изменяет память не имею отношения к JPOS драйверу, скорее к виндовому.
В принтере 16 типов оплаты.
1 – сумма по чеку наличными, 1031
2 по 13 – сумма по чеку безналичными, 1081
14 – сумма по чеку предоплатой (зачетом аванса и (или) предыдущих платежей), 1215
15 – сумма по чеку постоплатой (в кредит), 1216
16 – сумма по чеку (БСО) встречным предоставлением, 1217

То, что в принтере по умолчанию указаны названия типов оплаты как платежных систем ни на что не вилияет(кроме мб текста на чеке), любой тип оплаты с 2 по 13 в итоге приведет к отправке в ОФД безналичной оплаты. Название типов оплаты можно поменять, если они у Вас печатаются на чеке.
