### ISSUE TITLE
Ошибка 94 при печати чеков коррекции для возврата прихода/возврата расхода

### ISSUE THREAD

**Issue by dseredkin** [shtrih-m/javapos_shtrih#115]
Здравствуйте, по примеру [javapos_shtrih/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java ](https://github.com/shtrih-m/javapos_shtrih/blob/758a58ab5a261372586d3a9e9d4b84de58a19a6a/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L113) пытаемся напечатать чек коррекции и сталкиваемся со следующей ситуацией для разных типов чеков:
1) Приход - все печатается, ОК
2) Возврат прихода - выдает ошибку 94, ККТ: Неверная операция
3) Расход - все печатается, ОК
4) Возврат расхода - выдает ошибку 94, ККТ: Неверная операция
То есть, для **всех чеков возврата** получаем ошибку 94. Смена на момент печати открыта. Хотелось бы уточнить, какие могут быть причины, почему такая ошибка возникает? 
Ниже прилагаю пример, как пытались распечатать чек коррекции для возврата прихода
```java
private ShtrihFiscalPrinter printer;
...


FSStatusInfo fsStatus = printer.fsReadStatus();
if (fsStatus.getDocType().getValue() != FSDocType.FS_DOCTYPE_NONE)
    printer.fsCancelDocument();
printer.resetPrinter();
printer.fsStartCorrectionReceipt();

printer.fsWriteOperationTag(1203, "5406194003  ");

printer.fsWriteTag(1177, "Тест");

printer.fsWriteTag(1178, /*07.10.2020*/1602028800L, 4);

printer.fsWriteTag(1179, "1");
printer.fsPrintCorrectionReceipt3(
        /*Самостоятельно*/0,
        /*Возврат прихода*/2,
        100000,
        0,
        100000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        /*ОСН*/1
);
```

**Comment by nyxiscoo1** [comment]
Здравствуйте, чеки коррекции для возвратов не предусмотрены для ФФД 1.05, они появились только в ФФД 1.1 и они не печатаются этими методами.
