### ISSUE TITLE
1104 тег

### ISSUE THREAD

**Issue by Andrway** [shtrih-m/javapos_shtrih#116]
Здравствуйте, подскажите, пожалуйста, что нужно сделать, чтобы "сумма с ндс 0%" с чека на скане была 0?

printer.printRecItem(PAY_CATALOG_SUM_LABEL, check.getSubscriptionInfo().CatalogSum, 12, 3, 0, "");
printer.printRecItem(PAY_TARIFF_SUM_LABEL, check.getSubscriptionInfo().TariffSum, 12, 1, 0, "");

printer.printRecTotal(finalTotal, finalTotal, "");
printer.endFiscalReceipt(false);

[SCAN_20200923_085019673 (3).pdf](https://github.com/shtrih-m/javapos_shtrih/files/5368366/SCAN_20200923_085019673.3.pdf)

**Comment by Andrway** [comment]
Хотелось бы узнать это баг драйвера или ошибка с моей стороны

**Comment by nyxiscoo1** [comment]
Добрый день.
На фото документ сформирован правильно. В этом поле указывается не сумма налога(она всегда 0), а сумма подлежащая обложению им, все как написано сумма с НДС 0%.

**Comment by Andrway** [comment]
Спасибо большое
