### ISSUE TITLE
Некорректно работает  writeTable или readTable

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#12]
При помощи команд записываю и читаю данные из таблиц
```
printer.wrtiteTable(4, 1..14, 1, "Текст");
printer.readTable(4, 1..14, 1)
```
Чтение и запись происходят без ошибок
Если записать данные и считать их то отображаются записанные данные
Если записать, разорвать соединение, подключиться и считать, то возвращает пустые строки

Я так понял что запись в таблицу не происходит, а данные кешируются в драйвере

**Comment by nyxiscoo1** [comment]
Запись в таблицу работает как положено.
Данные в таблице 4, "Текст в чеке" затирает сам драйвер, в нем реализована логика печати заголовка, соответственно в эту таблицу драйвер запишет данные которые ему нужны для печати заданного заголовка.
Мое утверждение можно легко проверить, например, записав данные в таблицу 5 "Типы оплаты".

**Comment by mifkamaz** [comment]
Да, там все ок

Получается нужно в  jpos файле что то указать? Что бы изменить клише и рекламный текст

**Comment by nyxiscoo1** [comment]
Через jpos.xml можно задать количество строк хидера и трэйлера, с помощью драйвера можно их установить методом printer.setHeaderLine(i, lines[i - 1], false);

```
<!-- Number of header lines -->
<prop name="numHeaderLines" type="String" value="2"/>
<!-- Number of trailer lines -->
<prop name="numTrailerLines" type="String" value="0"/>
```
