### ISSUE TITLE
Печать копии произвольного (не последнего) чека.

### ISSUE THREAD

**Issue by gigacoderr** [shtrih-m/javapos_shtrih#122]
Подскажите, пожалуйста, можно ли вывести на печать копию произвольного чека? 
Если да - то каким образом это можно сделать?

Либо альтернативные варианты, если нет прямой возможности.

Спасибо заранее.

**Comment by nyxiscoo1** [comment]
СКЛ может напечатать какое-то подобие произвольного чека. Правда это не очень надежный и достаточно кривой на мой взгляд механизм.

Если нужна именно копия чека, то нужно сохранять все данные по чеку у себя в приложении, никаких штатных механизмов печати произвольного чека ни в драйвере ни в ККТ нет.

**Comment by gigacoderr** [comment]
То есть, если я правильно понимаю, нужно при формировании чека сохранить его текстовую версию и потом распечатывать её нефискальными строками?

**Comment by nyxiscoo1** [comment]
Я не совсем понимаю, что значит текстовая версия.
Для печати дубликата нужны исходные данные чека(которые ПО передает в драйвер) + данные ККТ + фискальные данные чека полученные после его формирования. Вот их сохранить и на основе их уже при печати дубликата сформировать чек в виду текста и отправить его на печать.

**Comment by gigacoderr** [comment]
Я понял вас. Спасибо большое за консультацию.
