### ISSUE TITLE
релиз 614 не печатаются признаки агента

### ISSUE THREAD

**Issue by VladislavKhambikov** [shtrih-m/javapos_shtrih#127]
Добрый день 
релиз javapos_shtrih 614, не печатаются признаки агента

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Нужна дополнительная информация: значения таблиц ФР и лог драйвера.

**Comment by VladislavKhambikov** [comment]
https://disk.yandex.ru/d/tYdOx_N7pwlTNQ

**Comment by VladislavKhambikov** [comment]
Добрый день. Можно узнать сроки решения проблемы?

**Comment by VitalyKravtsov2016** [comment]
Поправлено в версии 618

**Comment by dseredkin** [comment]
@VitalyKravtsov2016, здравствуйте. У нас возникла похожая ошибка. Обновились до версии 618. ИНН, телефон и наименование поставщика действительно стали выводиться, но заметили проблему с дублированием ИНН.

Попробовали напечатать чек таким образом.
```java
printer.resetPrinter();
printer.setFiscalReceiptType(FPTR_RT_SALES);
printer.beginFiscalReceipt(true);
TLVWriter writer = new TLVWriter();

final int phoneTag = 1171;
final int supplierNameTag = 1225;

writer.add(phoneTag, "+79616195832");
writer.add(supplierNameTag, "ТестТест");
final int supplierDataTag = 1224;
printer.fsWriteOperationTag(supplierDataTag, writer.getBytes());

final int innTag = 1226;
printer.fsWriteOperationTag(innTag, "3664069397  ");
printer.printRecItem("Позиция1", 0, 1000, 1, 10000, "0");
printer.printRecTotal(10000, 10000, REC_TOTAL_CASH_DESCRIPTION);
printer.endFiscalReceipt(true);
```

Напечатался такой чек https://prnt.sc/12ifjyu

Как видно, ИНН продублировался . В чем может быть причина?
