### ISSUE TITLE
Изменение настроек прочитанных из jpos файла после подключения к устройству

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#13]
Имеется ли возможность изменить не критичные (рекламный текст, клише, пароль кассира) настройки подключения без переподключения к устройству?
Сейчас так:
1. Подключились к кассе
2. Захотели зменить клише и рекламу
3. Отключаемся от кассы
4. Редактируем jpos.xml
5. Подключаемся

А хочется так
1. Подключились к кассе
2. Редактируем клише и рекламу наприямую в инстансе принтера + редактируем jpos файл для сохранения настроек

**Comment by nyxiscoo1** [comment]
По поводу клише см. issue #12.

Пароль кассира и его имя можно задать так:
```
printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_USR_PASSWORD, newPassword);
printer.setPOSID("1", "Оператор Оператор");
```
Таким же способом можно задать пароли администратора и налогового инспектора:
```
 printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_TAX_PASSWORD, newPassword);
printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_SYS_PASSWORD, newPassword);
```

Их нужно задавать каждый раз после того как устройство enabled.
