### ISSUE TITLE
Неверная дата основания коррекции

### ISSUE THREAD

**Issue by dseredkin** [shtrih-m/javapos_shtrih#132]
Здравствуйте! При печати чека коррекции дата основания коррекции всегда равна сегодняшней независимо от того, какую передаем в тег 1178. Печатаем точно как в примере [FFD105Documents.java](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L113). Используем версию библиотеки 626. 

Как исправить эту проблему? Используем ФР АЗУР-01Ф.

**Comment by surkovnsk** [comment]
@VitalyKravtsov2016 Виталий, здравствуйте, вижу, что отвечали на другие наши обращения. Посмотрите пожалуйста вопрос выше. Подскажите к кому можно обратиться для его решения, если не к вам.

**Comment by dseredkin** [comment]
В версии драйвера 631 проблема решена. Если перейти на 631 и использовать [FFD105Documents.java](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L113) в качестве примера для печати чека коррекции, то будет возникать ошибка про неверные параметры. Нужно просто не передавать тэг 1177.
