### ISSUE TITLE
Ошибка 54, ККТ: Некорректные параметры в команде для данной реализации

### ISSUE THREAD

**Issue by vskabina** [shtrih-m/javapos_shtrih#140]
Здравствуйте! При печати чеков на команде FF46h выдается ошибка 54, ККТ: Некорректные параметры в команде для данной реализации. Ошибка начала появляться начиная с версии 634. Логи печати разных чеков приложены. Подскажите пожалуйста в чём проблема?
[log_service.txt](https://github.com/shtrih-m/javapos_shtrih/files/7744408/log_service.txt)
[log_income.txt](https://github.com/shtrih-m/javapos_shtrih/files/7744410/log_income.txt)
Используется АЗУР-01Ф

**Comment by Tango600** [comment]
#139, такой же вопрос

**Comment by anddever** [comment]
Присоединяюсь

**Comment by Tango600** [comment]
+1

**Comment by SergeantSergey** [comment]
+1

**Comment by Egorka100** [comment]
+1

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/shtrih-m/javapos_shtrih/releases/tag/639
