### ISSUE TITLE
Не работает повторная печать последнего чека

### ISSUE THREAD

**Issue by vladislav-larionov** [shtrih-m/javapos_shtrih#159]
При повторной печати последнего чека появляется ошибка `ErrorCode: 106, ErrorCodeExtended: 0, "THere is no documents to print", time = 1 ms`.
Воспроизводится на Штрих Мобайл (версия ПО: A.4,  сборка ПО: 20045) и на Штрих Нано ф (версия ПО: C.1,  сборка ПО: 159).
Если смотреть через драйвер на ПК, то платёж есть.
Проблема появилась с обновлением на версию [688](https://github.com/shtrih-m/javapos_shtrih/releases/tag/688). На 687 проблема тоже есть. С какой конкретно версии она появилась, к сожалению, не знаю.
[shtrih.log](https://github.com/shtrih-m/javapos_shtrih/files/10773768/shtrih.log)

Код вызова печати:
```kotlin
override fun ShtrihFiscalPrinter.repeatLastCheque() {
	try {
		printDuplicateReceipt()
	} catch (exception: JposException) {
		if (exception.errorCode != RECEIPT_PRINTING_ERROR_CODE
				|| exception.errorCodeExtended != DUPLICATE_ALREADY_PRINTED_ERROR_EXTENDED_CODE) {
			throw exception
		} else {
			logError(exception)
		}
	}
}
```

**Comment by VitalyKravtsov2016** [comment]
Ошибка, сегодня исправлю.

**Comment by VitalyKravtsov2016** [comment]
Поправил: https://github.com/shtrih-m/javapos_shtrih/releases/tag/689

**Comment by vladislav-larionov** [comment]
Ошибка с кодом 106 из описания действительно пропала. Но появилась другая - `JposException. ErrorCode: 114, ErrorCodeExtended: 389, "89, Документ открыт другим оператором"`.
При повторной попытке распечатать последний платёж появляется другая ошибка `JposException. ErrorCode: 114, ErrorCodeExtended: 386, "86, Нет документа для повтора"`.
[shtrih.log](https://github.com/shtrih-m/javapos_shtrih/files/10790408/shtrih.log)

**Comment by VitalyKravtsov2016** [comment]
Ошибку "86, Нет документа для повтора" выдает ФР. 
Задача драйвера подать команду "Повтор документа" - он это делает. 
В ФР не всегда есть копия последнего документа. Копия документа очищается
при отмене чека или при программировании некоторых полей таблиц. 
Приложению проще распечатать документ из своей базы.

**Comment by VitalyKravtsov2016** [comment]
Ошибка "89, Документ открыт другим оператором" возникает при попытке напечтать 
копию последнего чека с паролем системного администратора. Так сделано потому, 
что чек может быть напечатан с паролем оператора, а отчет печатается с паролем 
администратора. При подаче команды "Повтор документа" мы не знаем копия какого
документа в ФР - там может быть отчет с гашением и для него нужен пароль администратора. 
Странно, что для повтора чека не подходит пароль администратора.
Чтобы поправить можно в файле jpos.xml установить одинаковый пароль оператора и администратора:

<prop name="operatorPassword" type="String" value="30"/>

<prop name="sysAdminPassword" type="String" value="30"/>

**Comment by vladislav-larionov** [comment]
Ошибку 89 удалось поправить установкой одинаковых паролей оператора и администратора, спасибо.

Подскажите, пожалуйста, ошибка `ErrorCode: 114, ErrorCodeExtended: 386, "86, Get error description", time = 2166 ms` эквивалентна ошибке `JposException. ErrorCode: 114, ErrorCodeExtended: 386, "86, Нет документа для повтора"`? 
[shtrih.log](https://github.com/shtrih-m/javapos_shtrih/files/10791352/shtrih.log)
Она сразу появляется при попытке напечаталь повторный чек, без ошибки с кодом 89. На старых версиях драйвера такого поведения не было.
Проблема проявилась на PAX A930 (Версия ПО: C.2, Сборка ПО: 37240). На штрих мобайл и штрих нано всё в порядке.

**Comment by VitalyKravtsov2016** [comment]
Ошибка, там должно читаться описание ошибки из ФР. Сейчас поправлю.

**Comment by VitalyKravtsov2016** [comment]
Поправил: https://github.com/shtrih-m/javapos_shtrih/releases/tag/690

**Comment by Tango600** [comment]
Теперь ошибка 
Ошибка при печати X-отчёта: Attempt to invoke virtual method 'void com.shtrih.fiscalprinter.command.TextDocumentFilter.printXReport()' on a null object reference

**Comment by VitalyKravtsov2016** [comment]
Странно, сейчас поправлю.

**Comment by Tango600** [comment]
![image](https://user-images.githubusercontent.com/5998520/224692806-dd49481f-3fd6-415e-acda-b1dccb0d533e.png)
А вот и причина.
