### ISSUE TITLE
Ставка НДС

### ISSUE THREAD

**Issue by Tieru** [shtrih-m/javapos_shtrih#16]
Здравствуйте, подскажите пожалуйста, как передать ставку НДС? Например, позиции "Без НДС", "НДС 0%", "НДС 18%". Либо укажите на доку, где есть пример кода/описание

**Comment by nyxiscoo1** [comment]
Здравствуйте!

Методы, например, printRecItem принимают параметр vatInfo, который может иметь следующие значения:
0 - без ндс
1 - ндс 18%
2 - ндс 10%
3 - ндс 0%
4 - без ндс
5 - ндс 18/118
6 - ндс 10/110

// Без НДС
printer.printRecItem("1 3493909 Бланк игр.ком.ВГЛ4 Спорт(Жил.л", 1, 1000, 4, 1, "");
// НДС 0%
printer.printRecItem("2 3493909 Бланк игр.ком.ВГЛ4 Спорт(Жил.л", 1, 1000, 3, 1, "");
// НДС 18%
printer.printRecItem("3 3493909 Бланк игр.ком.ВГЛ4 Спорт(Жил.л", 1, 1000, 1, 1, "");

**Comment by Tieru** [comment]
Спасибо!

**Comment by goldenluk** [comment]
Здравствуйте, как быть, если нужно чтобы вызов printRecItem с параметром price = 0 всё равно печатал запись. Сейчас такой вызов не печатает ничего
