### ISSUE TITLE
Замедлилось время выполнения некоторых функций драйвера

### ISSUE THREAD

**Issue by vladislav-larionov** [shtrih-m/javapos_shtrih#162]
На последних версиях драйвера увеличилось время выполнения некоторых функций драйвера примерно в 2 раза.
Замедление работы сильно заметно при открытии смены и печати Z-отчёта.
Проблему заметили при переходе с версии 617 на 692. 

Такое ощущение, что замедлилось подключение к устройству через драйвер. Не могли бы Вы посмотреть и прокомментировать всё ли в порядке? 

[logs.zip](https://github.com/shtrih-m/javapos_shtrih/files/11145314/logs.zip)

Время работы некоторых операций:
Версия драйвера 617:
* открытие смены 30 сек (сопряжение 15 сек + печать Х-отчёт 15 сек)
* проведение услуги 37 сек (Печать двух чеков)
* Z-отчёт 21 сек

Версия драйвера 692:
* открытие смены 50 сек (сопряжение 27 сек + печать Х-отчёт 13 сек)
* проведение услуги 45 сек (Печать двух чеков)
* Z-отчёт 40 сек

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/shtrih-m/javapos_shtrih/releases/tag/695

**Comment by vladislav-larionov** [comment]
Добрый день. Проблема со скоростью печати пропала, спасибо. Однако в логах появилось несколько ошибок:
1. При сопряжении и при печати z-отчёта в логе проскакивает ошибка `Attempt to invoke virtual method 'java.lang.String com.shtrih.fiscalprinter.command.FieldInfo.bytesToField(byte[], java.lang.String)' on a null object reference`.
2. При проведении платежа во время печати чека появляется ошибка `Attempt to invoke virtual method 'long com.shtrih.fiscalprinter.command.FSDocument.getDocSign()' on a null object reference`.

На функциональность они вроде не влияют, но раньше их не было.
[shtrih.log](https://github.com/shtrih-m/javapos_shtrih/files/11197507/shtrih.log)

**Comment by VitalyKravtsov2016** [comment]
Сегодня поправлю.

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/shtrih-m/javapos_shtrih/releases/tag/696

**Comment by Tango600** [comment]
Теперь ошибка 80 при открытии или закрытии смены.

**Comment by VitalyKravtsov2016** [comment]
Лог можно посмотреть?

**Comment by Tango600** [comment]
Лог в #163 тикете.
