### ISSUE TITLE
80, Идет печать предыдущей команды

### ISSUE THREAD

**Issue by Tango600** [shtrih-m/javapos_shtrih#163]
При закрытии смены.
Штрих-Мобайл, 20041. Дата ПО: 16.10.2018, драйвер 696.
Уточнение: В момент закрытия смены закончилась бумага, а повторные попытки давали такие ошибки. На драйвере версии 988 закрывается.
`
04-19 17:28:02.164 D/BluetoothSocket(17603): close() this: android.bluetooth.BluetoothSocket@57bcd9c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@10443a5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@20b437amSocket: null, mSocketState: CLOSED
04-19 17:28:02.166 D/BluetoothSocket(17603): close() this: android.bluetooth.BluetoothSocket@48fe2ec, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@6efb6b5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@2ba214amSocket: null, mSocketState: CLOSED
04-19 17:28:02.422 W/pool-1-thread-5(17603): type=1400 audit(0.0:58126): avc: granted { append } for name="2023-04-19_14240031.txt" dev="sdcardfs" ino=153322 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
04-19 17:28:02.428 W/System.err(17603): jpos.JposException: 80, Идет печать предыдущей команды
04-19 17:28:02.432 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:8)
04-19 17:28:02.433 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:1)
04-19 17:28:02.433 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:2)
04-19 17:28:02.433 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:3)
04-19 17:28:02.433 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.printZReport(FiscalPrinterService.java:3)
04-19 17:28:02.433 W/System.err(17603): 	at jpos.FiscalPrinter.printZReport(FiscalPrinter.java:2)
04-19 17:28:02.433 W/System.err(17603): 	at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.printZReport(Unknown Source:2)
04-19 17:28:02.433 W/System.err(17603): 	at nppltt.ppsmobileclient.kkmManagment.shtrih.b.a(R8$$SyntheticClass:7)
04-19 17:28:02.433 W/System.err(17603): 	at nppltt.ppsmobileclient.kkmManagment.shtrih.ShtrihKkmManager.U(ShtrihKkmManager.java:7)
04-19 17:28:02.433 W/System.err(17603): 	at nppltt.ppsmobileclient.kkmManagment.shtrih.ShtrihKkmManager.J(ShtrihKkmManager.java:13)
04-19 17:28:02.433 W/System.err(17603): 	at nppltt.ppsmobileclient.kkmManagment.shtrih.g.a(Unknown Source:6)
04-19 17:28:02.433 W/System.err(17603): 	at com.google.android.material.datepicker.c.run(R8$$SyntheticClass:4)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
04-19 17:28:02.433 W/System.err(17603): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-19 17:28:02.433 W/System.err(17603): 	at java.lang.Thread.run(Thread.java:784)
04-19 17:28:02.434 W/System.err(17603): Caused by: com.shtrih.fiscalprinter.DeviceException: 80, Идет печать предыдущей команды
04-19 17:28:02.434 W/System.err(17603): 	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.check(SMFiscalPrinterImpl.java:2)
04-19 17:28:02.434 W/System.err(17603): 	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.execute(Unknown Source:4)
04-19 17:28:02.434 W/System.err(17603): 	at com.shtrih.fiscalprinter.SMFiscalPrinterImpl.printZReport(SMFiscalPrinterImpl.java:8)
04-19 17:28:02.435 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.printZReport(FiscalPrinterImpl.java:12)
04-19 17:28:02.435 W/System.err(17603): 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.printZReport(FiscalPrinterService.java:2)
04-19 17:28:02.435 W/System.err(17603): 	... 14 more
04-19 17:28:02.434 W/pool-1-thread-5(17603): type=1400 audit(0.0:58128): avc: granted { append } for name="2023-04-19_14240031.txt" dev="sdcardfs" ino=153322 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
04-19 17:28:02.449 E/ion     (17603): ioctl c0044901 failed with code -1: Invalid argument
04-19 17:28:02.450 I/chatty  (17603): uid=10175(nppltt.ppsmobileclient) RenderThread identical 1 line
04-19 17:28:02.450 E/ion     (17603): ioctl c0044901 failed with code -1: Invalid argument
`

**Comment by Tango600** [comment]
При открытии наблюдается такая же проблема.

**Comment by Tango600** [comment]
[IT.zip](https://github.com/shtrih-m/javapos_shtrih/files/11311673/IT.zip)

**Comment by Tango600** [comment]
> Лучше лог в виде файла прикрепить.
Достаточно данных? Больше нет.

**Comment by Tango600** [comment]
+1

**Comment by vladislav-larionov** [comment]
У нас есть проблема с аналогичной ошибкой `80, Идет печать предыдущей команды`. Правда у нас её появление не зависит от окончания ленты. 
К сожалению, точных шагов по воспроизведению не могу приложить, так как не понимаю от чего зависит её появление. Ошибка появляется при закрытии смены. Появляется, наверное, один раз на 15-20 закрытий смены.
Проблема проявляется на штрих мобайл с версией драйвера 697.
[shtrih_697.log](https://github.com/shtrih-m/javapos_shtrih/files/11654264/shtrih_697.log)
[shtrih_696.log](https://github.com/shtrih-m/javapos_shtrih/files/11654276/shtrih_696.log)
