### ISSUE TITLE
Типы оплаты не прописываются в таблицу ККТ

### ISSUE THREAD

**Issue by jagrdev** [shtrih-m/javapos_shtrih#18]
Типы оплаты более 4-х не прописываются в таблицу ККТ, когда флаг tableMode = 0 в jpos.xml
Нашел код в FptrParameters.load думаю это влияет:
        // paymentNames
        String paymentName;
        String propertyName;
        paymentNames.clear();
        for (int i = 1; i <= 4; i++) {
            propertyName = "paymentName" + String.valueOf(i);
            if (entry.hasPropertyWithName(propertyName)) {
                paymentName = (String) entry.getPropertyValue(propertyName);
                paymentNames.add(new FptrPaymentName(i, paymentName));
            }
        }

**Comment by nyxiscoo1** [comment]
Добрый день. Да, действительно это баг оставшийся от старых версий устройств.
Исправил.

**Comment by nyxiscoo1** [comment]
Выложил релиз 460 содержащий данное изменение.
