### ISSUE TITLE
В КЛ так и пишет "ТАРОЙ"

### ISSUE THREAD

**Issue by iboxmpos** [shtrih-m/javapos_shtrih#20]
Не исправлено вычитывание, внесенных в таблицу ККТ, типов оплат для отражения в контрольной ленте. Вместо, указанного в порядковом номере 3 таблицы, типов оплаты (у нас зашито "ПРЕДОПЛАТОЙ") пишет "ТАРОЙ"

Проверено на JPOS_459 в ККТ MOBILE-Ф с прошивкой 20019

**Comment by nyxiscoo1** [comment]
Это в СКЛ сформированной после обновления драйвера?

**Comment by iboxmpos** [comment]
Да, именно!

Kind regards, 

Dmitry Nazarov,
Head of integration support
+7 (926) 526-77-55
www.iboxmpos.com

**Comment by iboxmpos** [comment]
Паш, исправления по КЛ будут?

**Comment by nyxiscoo1** [comment]
Будут завтра-послезавтра.

**Comment by iboxmpos** [comment]
Отлично, спасибо! Ждем JPOS461 )

 

Best regards,

Dmitry Nazarov, 

DCTO at Smartfin JSC (2can&ibox brands)

8 800 303-45-26 (доб. 222)

8 926-526-77-55

Skype: dimitry.nazaroff

 



 

Moscow, Andropova avenue, 18 bldg. 7, office 804

 <http://www.2can.ru/> www.2can.ru |  <http://www.iboxmpos.com/> www.iboxmpos.com

**Comment by nyxiscoo1** [comment]
https://github.com/shtrih-m/javapos_shtrih/releases/tag/461
Исправил.

**Comment by iboxmpos** [comment]
Супер, спасибо! Попробуем впихнуть в текущий релиз iboxPro

Kind regards, 

Dmitry Nazarov,
Head of integration support
+7 (926) 526-77-55
www.iboxmpos.com

**Comment by iboxmpos** [comment]
Проверено, исправлено!
