### ISSUE TITLE
ШТРИХ-MOBILE-Ф не отдает длинный ЗН ККТ

### ISSUE THREAD

**Issue by iboxmpos** [shtrih-m/javapos_shtrih#21]
Паш, подскажи, заводской номер можем вычитывать полный?
Сейчас режет до 5 последних символов

Зав. Номер (старшее слово) 2,5: 0000…9999 (FFh FFh – заводской номер не введен)

**Comment by nyxiscoo1** [comment]
Можем. Например из таблицы фискального накопителя:
printer.readTable(14,1,1);

**Comment by iboxmpos** [comment]
А из самого ККТ без ФН можем читать? Есть клиенты на ЕНВД, у которых нет ФН

 

Вообще задача состоит в том, что бы, по итогу регистрации каждого ПРИХОДА/ВОВЗРАТА ПРИХОДА, получать итог операции, включая фискальные признаки чека и длинный номер ККТ, т.е. не вычитывать отдельно, а получать в итогах после операции.

 

Это возможно?

 

 

Best regards,

Dmitry Nazarov, 

DCTO at Smartfin JSC (2can&ibox brands)

8 800 303-45-26 (доб. 222)

8 926-526-77-55

Skype: dimitry.nazaroff

 



 

Moscow, Andropova avenue, 18 bldg. 7, office 804

 <http://www.2can.ru/> www.2can.ru |  <http://www.iboxmpos.com/> www.iboxmpos.com

**Comment by nyxiscoo1** [comment]
> А из самого ККТ без ФН можем читать? Есть клиенты на ЕНВД, у которых нет ФН.

Вообще данная таблица это единственное место где можно вычитать полный заводской номер по моему представлению.

Ты хочешь сказать, что у тебя есть устройство без ФН(а с чем? с ЭКЛЗ?) у которого длинный номер и нет такой таблицы содержащей полный номер?

> Вообще задача состоит в том, что бы, по итогу регистрации каждого ПРИХОДА/ВОВЗРАТА ПРИХОДА, получать итог операции, включая фискальные признаки чека и длинный номер ККТ, т.е. не вычитывать отдельно, а получать в итогах после операции.

Я если честно не совсем понимаю, если нет ФН, то нет и ФП, при наличии ЭКЛЗ будет КПК и он будет получаться другим способом.
ФП и номер ФД можно прочитать используя команду fsFindDocument. Номер можно прочитать из таблицы, он не меняется.
Сам ФР при выполнении закрытия чека присылает ФП и номер ФД, но они спрятаны за интефрейсом JPOS, можно их сохранить и сделать метод их получения, без обращения к устройству.

**Comment by iboxmpos** [comment]
1. Не соглашусь с тобой, что можно только из таблицы читать ЗН ККТ. Поправь меня, если намудрил…

Вот, что есть в протоколе 2.0:

Запрос длинного заводского номера и длинного РНМ Команда: 0FH. Длина сообщения: 5 байт. Пароль оператора (4 байта) Ответ: 0FH. Длина сообщения: 16 байт. Код ошибки (1 байт) Заводской номер (7 байт) 00000000000000…999999999999991 РНМ (7 байт) 00000000000000…999999999999991

 

Вот, что есть в JPOS:

 Чтение серийного номера ФР

/** Read device serial number **/

public static final int SMFPTR_DIO_READ_SERIAL = 0x16*;*

public String readSerial*()* throws JposException {

    String*[]* serial = new String*[*1*];*

    directIO*(SmFptrConst.SMFPTR_DIO_READ_SERIAL,* null, serial*);*

    return serial*[*0*];*

или

public String  getPhysicalDeviceName*()* throws JposException*;*

Возвращает строку вида "ШТРИХ-МИНИ-ФР-К, №12345678", то есть название устройства и его серийный номер

 

2.  Фиск. данные мы уже умеем получать после закрытия чека и, естественно, это только для клиентов с ФН.

Вопрос в том, как дополнить эти данные заводским номером ККТ.

 

 

 

Best regards,

Dmitry Nazarov, 

DCTO at Smartfin JSC (2can&ibox brands)

8 800 303-45-26 (доб. 222)

8 926-526-77-55

Skype: dimitry.nazaroff

 



 

Moscow, Andropova avenue, 18 bldg. 7, office 804

 <http://www.2can.ru/> www.2can.ru |  <http://www.iboxmpos.com/> www.iboxmpos.com

**Comment by nyxiscoo1** [comment]
Команда 0FH в Мобайле возвращает (55) Команда не поддерживается в данной реализации, версия 20024.
![image](https://user-images.githubusercontent.com/284666/29627847-266e8484-883c-11e7-8f74-69f4fb5c15a4.png)

Драйвер ФР, виндовый, в диалоге проверки связи с устройством делает так: определяет модель устройства и потом в зависимости от модели производит чтение таблицы.

**Comment by iboxmpos** [comment]
Принято, спасибо! Попробуем варианты, если что - сообщу!

**Comment by gevorg95** [comment]
Добрый день!

Я никак не могу получить полный номер фискального регистратора.

Я пробовал все методы выше: 
- `printer.readTable(14,1,1);` 
- `directIO*(SmFptrConst.SMFPTR_DIO_READ_SERIAL, null, serial*);`
- `getPhysicalDeviceName();`

Но они все возвращают только пятизначный значный номер...
