### ISSUE TITLE
Чтение расширенных денежных регистров

### ISSUE THREAD

**Issue by jagrdev** [shtrih-m/javapos_shtrih#22]
Подскажите, как правильно прочитать расширенные денежные регистры?
команда printer.readCashRegister(4152) возвращает 0.
Но при печати Z-отчета эти данные пробиваются в отчет.

**Comment by nyxiscoo1** [comment]
О каком устройстве идет речь?
Какая версия драйвера?

Проверил сейчас чтение расширенных регистров работает как положено.

**Comment by jagrdev** [comment]
Устройство: ШТРИХ-МОБАЙЛ-Ф
Версия прошивки: 20024 от 21.07.2017
Драйвер: ShtrihJavaPOS 460

**Comment by nyxiscoo1** [comment]
Это баг устройства, должно быть исправлено в 20026.

**Comment by nyxiscoo1** [comment]
Судя по описанию прошивки исправлено в 20026.

**Comment by jagrdev** [comment]
Спасибо, помогло
