### ISSUE TITLE
ГРОССЫ / Необнуляемая сумма продаж

### ISSUE THREAD

**Issue by iboxmpos** [shtrih-m/javapos_shtrih#23]
Паша, привет! Подскажи как получать необнуляемую сумму продаж в X/Z отчетах на ШТРИХ-MOBILE-Ф (прошивка 20019/20024)?
Это функционал будет/есть?... сейчас в отчетах не видим этого

**Comment by nyxiscoo1** [comment]
Привет, Дима!
Необнуляемая сумма хранится в 244 регистре.
Еще есть команда FE код F4 - это запрос необнуляемых сумм, но данная команда сейчас не поддержана драйвером, можем добавить, при необходимости.

**Comment by iboxmpos** [comment]
Не хотелось бы отдельную кнопку пилить для их печати, да и клиентов это не устроит.
Все хотят видеть этот регистр в в X/Z отчетах. Это в прошивку можно запихнуть?

**Comment by nyxiscoo1** [comment]
Передал твое пожелание разработчику устройства, он обещал добавить.

**Comment by iboxmpos** [comment]
Спасибо! Очень ждем... это как-то можно отконтролить?

**Comment by nyxiscoo1** [comment]
Готово 20027: 2. Добавлено поле 5 в табл.1 "ПЕЧАТЬ НЕОБНУЛЯЕМОЙ СУММЫ". Значение 1 печатает в суточных отчетах значение денежного регистра 244.

**Comment by iboxmpos** [comment]
Отлично, спасибо!

Скажи, если ККТ уже в эксплуатации на прошивках 20024 и 20019 и будут обновлены до 20027, то регистр будет отражать накопления с момента ввода ККТ в эксплуатацию или с момента обновления?

**Comment by nyxiscoo1** [comment]
Я задал на всякий случай вопрос разработчику устройства, но я так понимаю сумма должна остаться, ты же можешь ее и на 20024 прошивке запросить, было бы странно если б необнуляемая сумма обнулилась.

**Comment by nyxiscoo1** [comment]
Все как я и говорил:  регистр 244 и раньше накапливал сумму, которая сохраняется в eeprom, т.е. после перешивки необнул. сумма сохраняется.

**Comment by iboxmpos** [comment]
Отлично! Ждем прошивку. Пришли мне в личку, плиз!
Таск считаю закрытым, спасибо!
