### ISSUE TITLE
Неверное состояние принтера (com.shtrih.jpos.fiscalprinter.Fisca lPrinterState@1508d46d, ”FPTR_PS_FISCAL_RECEIPT_ENDING"

### ISSUE THREAD

**Issue by iboxmpos** [shtrih-m/javapos_shtrih#24]
При закрытие просроченной смены на Штрих-Mobile-Ф (20019/JPOS461) получаем сообщение об ошибке:
`Неверное состояние принтера (com.shtrih.jpos.fiscalprinter.Fisca lPrinterState@1508d46d, ”FPTR_PS_FISCAL_RECEIPT_ENDING"`

Как бороться?

**Comment by nyxiscoo1** [comment]
Есть лог?

**Comment by iboxmpos** [comment]
Как снять?

**Comment by nyxiscoo1** [comment]
Смотря как настроили логирование, драйвер шел в logback, а куда будут направлены его данные зависит от основного приложения. В примере в корень флешки должно логироваться.

**Comment by iboxmpos** [comment]
09-11 17:37:20.590: D/PrinterService(27969): -----------------
09-11 17:37:20.600: D/InputDispatcher(987): Focus left window: 28063
09-11 17:37:20.600: D/InputDispatcher(987): Focus entered window: 28063
09-11 17:37:20.600: D/PointerIcon(987): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:987 uid:1000
09-11 17:37:20.600: D/PointerIcon(987): setMouseCustomIcon IconType is same.101
09-11 17:37:20.600: D/PrinterService(27969): CloseShift {
09-11 17:37:20.600: D/PrinterService(27969): };
09-11 17:37:20.600: D/com.shtrih.jpos.fiscalprinter.FiscalPrinterService(27969): printZReport()
09-11 17:37:20.600: D/PrinterService(27969): com.shtrih.jpos.fiscalprinter.FiscalPrinterService | printZReport()
09-11 17:37:20.600: E/com.shtrih.jpos.fiscalprinter.JposExceptionHandler(27969): JposException. ErrorCode: 114, ErrorCodeExtended: 207, 'Неверное состояние принтера(com.shtrih.jpos.fiscalprinter.FiscalPrinterState@1508d46d, "FPTR_PS_FISCAL_RECEIPT_ENDING"'
09-11 17:37:20.610: E/c.s.j.f.JposExceptionHandler(27969): [Binder_2] JposException. ErrorCode: 114, ErrorCodeExtended: 207, 'Неверное состояние принтера(com.shtrih.jpos.fiscalprinter.FiscalPrinterState@1508d46d, "FPTR_PS_FISCAL_RECEIPT_ENDING"'

вот все что мы видим из лога

**Comment by nyxiscoo1** [comment]
Что-то мало, должны быть байты отправляемые в порт и пр.
Если лога нет, то можешь описать ситуацию, что делали до?

**Comment by iboxmpos** [comment]
Открыли смену... принтер лежал... смена просрочилась... хотели закрыть и получили ошибку!

**Comment by nyxiscoo1** [comment]
Чек не открывали?

**Comment by iboxmpos** [comment]
нет
