### ISSUE TITLE
ВОЗВРАТ ПРИХОДА, приводящий к минусовому регистру

### ISSUE THREAD

**Issue by iboxmpos** [shtrih-m/javapos_shtrih#26]
Провожу продажу наличными, закрываю смену, открываю смену, делаю Возврат операции, касса проводит Возврат, сообщения что в ККТ нет денег для выплаты не появляется. Снимаю Х отчет Выручка = -500.

Это правильное поведение?

Штрих-mobile-Ф
20019
ShtrihJavaPOS 465

**Comment by nyxiscoo1** [comment]
С точки зрения логики все выглядит разумно, ты за смену только вернул товар, поработал в минус.

**Comment by iboxmpos** [comment]
Согласен, что логично, но ранее (в JPOS411 и 455 и т.п.) ККТ выводил ошибку, что денег недостаточно и не давал фискализировать.

Вот я и пытаюсь понять так может быть с точки зрения технологии работы ККТ, бухгалтерии и налоговой... не у кого больше спросить)

**Comment by nyxiscoo1** [comment]
Все не совсем так, JPOS тут не при чем, ошибку выдавало устройство, сейчас не выдает, мб это поведение контролируется какой-то настройкой.

**Comment by iboxmpos** [comment]
а как узнать какой? кого спросить?

**Comment by iboxmpos** [comment]
Паш, привет! Есть понимание у кого это можно узнать?

**Comment by nyxiscoo1** [comment]
Можно спросить у разработчика устройства, но он сейчас в отпуске, я адресовал еще одному специалисту по ФРам этот вопрос, посмотрим, что он ответит.

**Comment by nyxiscoo1** [comment]
Дим, на какой версии прошивки выдавало ошибку, можешь сказать?

**Comment by nyxiscoo1** [comment]
[18:54:33] Андрей: НАЛ. в кассе неотрицательный, а ВЫРУЧКА может быть отрицательной при возвратах
[21:42:17] p.zhirkov: это нормальное поведение, которое ничем не регулируется?
[21:42:27] Андрей: всегда так было

**Comment by iboxmpos** [comment]
ОК, принято!
