### ISSUE TITLE
Печать жирной строки

### ISSUE THREAD

**Issue by DiukarevSergii** [shtrih-m/javapos_shtrih#38]
Подскажите пожалуйста как используя метод directIO напечатать жирную строку в чеке

**Comment by nyxiscoo1** [comment]
Если интересует именно DIO-команда, то нужно выполнить не одну команду, сперва нужно запомнить текущий шрифт, установить шрифт в нужное значение, в вашем случае 2, после этого напечатать строку методом printRecMessage, далее выставить шрифт в прежнее значение.

```
public void printRecMessage(String message, int fontNumber) throws JposException {
    int oldFontNumber = getFontNumber();
    try {
        setFontNumber(fontNumber);

        printRecMessage(encodeString(message));
    } finally {
        setFontNumber(oldFontNumber);
    }
}

public int getFontNumber() throws JposException {
    String value = getParameter(SmFptrConst.SMFPTR_DIO_PARAM_FONT_NUMBER);
    return Integer.parseInt(value);
}

public void setFontNumber(int value) throws JposException {
    setParameter(SmFptrConst.SMFPTR_DIO_PARAM_FONT_NUMBER, value);
}
```

Если использовать `ShtrihFiscalPrinter`, то можно просто вызвать метод `void printRecMessage(String message, int fontNumber)`

**Comment by DiukarevSergii** [comment]
К сожалению такой функционал в моем проекте недоступен. Подскажите а через directIO можно как то поменять шрифт?

**Comment by DiukarevSergii** [comment]
Благодаря вашей подсказке со шрифтом мне удалось напечатать У меня получилось напечатать большим шрифтом  int[] data = new int[1];
data[0] = 2;
directIO(code, data, text);

**Comment by nyxiscoo1** [comment]
Попробуйте другие, их 7 или 8 в зависимости от модели устройства и прошивки.

**Comment by DiukarevSergii** [comment]
Спасибо большое!
