### ISSUE TITLE
Проект-пример под Android - Android Sample 

### ISSUE THREAD

**Issue by hyperax** [shtrih-m/javapos_shtrih#39]
Добрый день!

1. Хорошим стандартом является предоставление рабочего проекта-примера для запуска драйверов. Если он есть, выложите, его, пожалуйста, в репозитории.

2. Имеется страничка Wiki, но там нет руководства о том, какие файлы и куда подключать, чтобы предложенные примеры кода работали.
Если такое руководство есть, пожалуйста, приложите его к репозиторию.

3. Было бы здорово указать перечень поддерживаемых ФР, которые позволят быстро начать тестирование и интеграцию. В частности, подойдет ли для тестов ШТРИХ-MOBILE-Ф (ШТРИХ-MOBILE-ПТК)?

Спасибо!

**Comment by nyxiscoo1** [comment]
Добрый день!

1. [tinyJavaPosTester](https://github.com/shtrih-m/javapos_shtrih/tree/master/Source/android/tinyJavaPosTester) пример приложения под Андроид.

2. Тут неплохо б уточнить, что имеется в виду под подключать: для возможности использовать драйвер нужно подключить aar и его зависимости, это архив  shtrihjavapos-android-ххх.zip в релизах.
Нужно брать последний релиз 491, т.к. до этого в указанном архиве отсутствовали зависимости архива.
Для работы самого драйвера нужно заставить работать JPOS, для этого нужно сформировать файл jpos.xml со свойствами, указать путь к этому файлу, пример можно глянуть в [JposConfig.java](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/JposConfig.java), далее создается объект `jpos.FiscalPrinter` и либо используется напрямую через интерфейс JPOS, либо через обертку `com.shtrih.fiscalprinter.ShtrihFiscalPrinter`.

3. Все ФРы производства Штрих-М поддерживаются. Единственный момент, что поддержка работы по USB пока носит характер экспериментальной.

**Comment by hyperax** [comment]
Спасибо за быстрый и развернутый ответ!
