### ISSUE TITLE
Состояние "Выдача данных" после вызова fsReadDocumentTLV.

### ISSUE THREAD

**Issue by seik0ixtem** [shtrih-m/javapos_shtrih#40]
После вызова метода `ShtrihFiscalPrinter.fsReadDocumentTLV` устройства остаются в состоянии "Выдача данных".

Лечим это тем, что в тест-драйвере "ФН" -> "Данные" жмём "Прочитать фиск. документ в TLV" (FNRequestFiscalDocument).
Эта команда выполняется успешно, но никаких данных не возвращает.
После этого устройство возвращается в "обычное" состояние.

Такая ситуация проявляется для ШТРИХ-ЛАЙТ-02Ф (Дата ПО: 20.12.2017).

**Comment by nyxiscoo1** [comment]
Да, проверил ШТРИХ-ЛАЙТ-02Ф ведет себя иначе нежели ШТРИХ-МОБАЙЛ-01Ф на котором я отлаживал чтение документов, ближе к вечеру выложу релиз с исправлениями.

**Comment by nyxiscoo1** [comment]
Исправлено в [499](https://github.com/shtrih-m/javapos_shtrih/releases/tag/499) релизе.
