### ISSUE TITLE
147, Восстановление ОЗУ прошло успешно, 16

### ISSUE THREAD

**Issue by mifkamaz** [shtrih-m/javapos_shtrih#41]
Принтер по непонятной причине начал выдавать ошибку

51, Некорректные параметры в команде, 1F1E00000005050001
51, Некорректные параметры в команде, 1F1E00000005060001
51, Некорректные параметры в команде, 1F1E00000005070001
51, Некорректные параметры в команде, 1F1E00000005080001
51, Некорректные параметры в команде, 1F1E00000005090001
51, Некорректные параметры в команде, 1F1E000000050A0001
51, Некорректные параметры в команде, 1F1E000000050B0001
51, Некорректные параметры в команде, 1F1E000000050C0001
51, Некорректные параметры в команде, 1F1E000000050D0001
51, Некорректные параметры в команде, 1F1E000000050E0001
51, Некорректные параметры в команде, 1F1E000000050F0001
51, Некорректные параметры в команде, 1F1E00000005100001
147, Восстановление ОЗУ прошло успешно, 16

В чем может быть проблема?
Версия драйвера 499, 496 и более поздняя

**Comment by nyxiscoo1** [comment]
Это Штрих-Мобайл? Похоже принтер вошел в состояние техобнуления. 
В итоге эти ошибки просто в логе или драйвер выкинул исключение?
Техобнуление производить драйвер должен автоматом при подключении.
