### ISSUE TITLE
Получение номера текущего открытого фискального документа

### ISSUE THREAD

**Issue by seik0ixtem** [shtrih-m/javapos_shtrih#45]
Мы решаем задачу фискализации онлайн платежей.
Нам нужно гарантировать, чтобы каждый чек был фискализован не более одного раза, 
вне зависимости от того, что нам передают более высокоуровневые алгоритмы.

Для этого применяем такой подход: 
1. Открываем чек.
2. Считываем текущий номер чека.
3. Сохраняем информацию о том, что чек с таким номером был открыт.
4. Заполняем чек, закрываем его.
5. Сохраняем информацию о том, что чек с таким номером был закрыт.

Если происходит сбой в автоматике на любом из этапов после 2го, 
то мы по номеру чека можем узнать, был ли чек закрыт и считать из 
устройства данные фискализации.

Для получения номера чека используем fsReadStatus().getDocNumber().
Используя этот номер позже легко можно считать данные по этому чеку в любой момент.

Проблема возникла на втором этапе: текущий номер чека заполняется только после 
закрытия чека, т.е. после вызова метода endFiscalReceipt().

Есть ли какой-нибудь способ получить номер открытого, но ещё не закрытого чека?

**Comment by seik0ixtem** [comment]
Да, рассматривали такой вариант, но очень не хочем его использовать.

Т.е. получается, это специфика прошивки штрихов?

**Comment by nyxiscoo1** [comment]
Штрих тут в моем понимании не причем, запрос fsReadStatus возвращает данные напрямую из ФН без дополнительной их обработки устройством.

Я могу предположить, что если чей-то ФР возвращает при открытом документе увеличенный номер он внутри делает +1 сам, т.к. сам ФН возвращает номер ФД только после отправки ему команды завершения формирования чека.

**Comment by nyxiscoo1** [comment]
Если имеется в виду какой-нибудь параметр который можно передать в чек или получить из открытого чека, по которому в последствии можно узнать номер ФД, то нет, ФФД не предусматривает никаких полей в которые можно писать произвольные значения, а ФР не хранит никаких ассоциированных с чеком данных.

Конечно может быть всякое, но мне видится маловероятным такое кардинальное изменение поведения ФН в будущем, проверил на самом свежем ФН который у меня есть fn debug v 2.12 он себя ведет аналогично предыдущим.

**Comment by seik0ixtem** [comment]
Грустно, конечно.

Спасибо за ответ!
