### ISSUE TITLE
Тэги 1212, 1214

### ISSUE THREAD

**Issue by goldenluk** [shtrih-m/javapos_shtrih#48]
Добрый день, возник вопрос касательно тегов 1212(Признак предмета расчета), 1214(Признак способа расчета).
При использовании fsWriteTag() теги вешаются на весь чек в конце.
Требуется чтобы данные теги включались в состав 1059, и были вот здесь внутри рядом с 1023, 1030 и т.д:
(Скриншот из офд)
![l_85fd tmp](https://user-images.githubusercontent.com/25905825/42869546-917ee9a6-8a9f-11e8-9cd0-f54134bb5068.PNG)
Не понимаю как вообще формируется 1059 и откуда берёт данные и как в него что-то добавить.
Ниже печать айтемов чека
![default](https://user-images.githubusercontent.com/25905825/42869619-c61139d0-8a9f-11e8-9fe6-923e03682002.PNG)
Видимо где-то в printRecItem это происходит.

Грубо говоря, нужно перетащить теги как-то вот так:
![default](https://user-images.githubusercontent.com/25905825/42869925-a7734e5e-8aa0-11e8-8393-aa463bee9d41.png)

Подскажите, пожалуйста, как быть.
Спасибо

**Comment by goldenluk** [comment]
`      

        printer.setFiscalReceiptType(FiscalPrinterConst.FPTR_RT_SALES);
        printer.beginFiscalReceipt(true);

        printer.printNormal(FiscalPrinterConst.FPTR_S_RECEIPT, receipt.getReceipt());

        final String unitName = receipt.getType() == Receipt.Type.SELL ? "Оплата" : "Возврат";

        printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_PAYMENT_TYPE, 4);
        printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_SUBJECT_TYPE, 4);

        printer.printRecItem("Приём платежа", receipt.getTotalSum() - receipt.getCommissionSum(), 0, 0, 0, unitName);
        printer.printRecItem("Размер вознаграждения", receipt.getCommissionSum(), 0, receipt.getVatInfo(), 0, unitName);
    
        printer.printRecTotal(receipt.getTotalSum(), receipt.getTotalSum(), "0");
        printer.endFiscalReceipt(false);`

Делаю вот так, ни на чеке, ни в офд не вижу тегов 1212, 1214. Не пойму, что я делаю не так, драйвер самый свежий

**Comment by nyxiscoo1** [comment]
Странно.
1. Какой принтер? Если это мобайл, то под какую версию ФФД он зафискализирован и какая версия прошивки?
2. На чеке он печататься не будет даже если передан, если есть возможность, то нужно прочитать TLV документа, это можно сделать драйвером ФР для винды, либо tinyJavaPosTester там есть кнопка Read document TLV и в выведенных данных посмотреть на тэг предмет расчета.

**Comment by nyxiscoo1** [comment]
На скрине с чтением тлв не доходит до предмета расчета, нужно из лога взять полную версию.

> Мобайл-ф, фискализирован под ФФД 1.0, версию прошивки не могу в текущий момент сказать

Вот это многое объясняет. Возможно 2 варианта: либо мобайл при ФФД 1.0 не передает эти параметры, либо прошивка настолько стара, что не поддерживает 1.05 и тэги 1212 и 1214.

**Comment by nyxiscoo1** [comment]
Прошивка тэги поддерживать должна.

> Не могу найти в логах данные как на скрине

Да, это я неправильно выразился, эти данные в лог не пишутся, они пишутся в logcat.

**Comment by nyxiscoo1** [comment]
Проверил на своем мобайле, он просто не пишет тэги 1212 и 1214 если ФФД 1.0

**Comment by goldenluk** [comment]
Принял, спасибо
