### ISSUE TITLE
TLVTags

### ISSUE THREAD

**Issue by sevenwind** [shtrih-m/javapos_shtrih#49]
Добрый день. У некоторых тегов не заполнен printName.
Можете ли вы заполнить это поле у тегов 1222 и 1225?

**Comment by nyxiscoo1** [comment]
Добрый день!
Могу, только как их заполнить? В "Заголовок реквизита ФД в ПФ" у них стоит прочерк.

**Comment by sevenwind** [comment]
Там много тегов без "Заголовок реквизита ФД в П". В классе у них printName стоит. Например:
tag = this.add(1057, "признак платежного агента", "ПРИЗН. ПЛАТ. АГЕНТА", TLVType.itByte, 1);
http://prntscr.com/kttanj

Возможно, стоит так же заполнить?

**Comment by sevenwind** [comment]
НАИМЕН. ПОСТАВЩИКА:Агент 007
ИНН ПОСТАВЩИКА:7728690708
ТЛФ. ПОСТ.:+70110001111
ПРИЗН. АГ. ПО ПРЕДМ. РАСЧ:64

Это что выводит виндовый драйвер штриха. Можно использовать эти же имена.

**Comment by nyxiscoo1** [comment]
Я изучу возможность внесения данного изменения. Можете сказать для чего Вам это нужно?

**Comment by sevenwind** [comment]
Для вывода данной информации в чеке. Можете сориентировать по срокам?

**Comment by nyxiscoo1** [comment]
Постараюсь сегодня либо завтра. Ее же согласно ФФД не нужно выводить в чеке. Вы сами напишете этот механизм?

**Comment by sevenwind** [comment]
Если я не ошибаюсь - есть набор обязательных полей - остальное уже по желанию. Какой именно механизм Вы подразумеваете? Я устанавливаю нужные теги только. И в чеке они выводятся без названия поля: ":Имя_поставщика"

**Comment by nyxiscoo1** [comment]
> И в чеке они выводятся без названия поля: ":Имя_поставщика"

Я так понимаю у Вас включена печать тэгов и это ее рук дело? Если так, то это баг, т.к. данный тэг вообще не должен печататься и, в данной ситуации, исправлением мне видится не добавление printName, а исключение тэга из печатаемых.

**Comment by sevenwind** [comment]
Почему не должен печататься? Где это написано? Я уже сам запутался... Печатаемые теги определяются настройками у нас или в Вашем драйвере?

**Comment by nyxiscoo1** [comment]
> Почему не должен печататься?

Посмотрел еще раз ФФД, он может печататься, хотя это и не обязательно делать, т.к. в поле "Обяз." у него 7, и как это должно делаться в печатной форме не сказано явно, есть только формат для электронной, там просто должно быть имя поставщика, без названия тэга.

> Печатаемые теги определяются настройками у нас или в Вашем драйвере?

В драйвере есть функция которая ответственна за печать тэгов.

Проконсультировался как у нас реализована печать этого тэга в ККТ, это просто строка печатаемая после телефона поставщика.

Вот пример чека, я сделаю так же:
![scv_15368323290876632427695597676887](https://user-images.githubusercontent.com/284666/45481335-f4adce80-b753-11e8-84a0-fa62f0ecf672.jpg)

**Comment by sevenwind** [comment]
Тогда, возможно, стоит убрать ":" перед полями у которых нет printName?

**Comment by sevenwind** [comment]
Не знаю, нужно ли это: Выравнивания по правому краю для значений тегов нет тоже(если ориентироваться на Ваше фото - строку с ТЛФ.  ПОСТ.)

**Comment by nyxiscoo1** [comment]
Я этого не планировал, только исправить текущее некорректное поведение.

**Comment by nyxiscoo1** [comment]
Выложил релиз [540](https://github.com/shtrih-m/javapos_shtrih/releases/tag/540).

**Comment by sevenwind** [comment]
Спасибо!
