### ISSUE TITLE
Ширина ленты в символах

### ISSUE THREAD

**Issue by tehreh1uneh** [shtrih-m/javapos_shtrih#52]
Здравствуйте, подскажите, возможно ли получить ширину ленты в символах?

**Comment by nyxiscoo1** [comment]
Здравствуйте, да, есть метод `int getTextLength(int fontNumber)`, либо через DIO-команду напрямую:
```
int[] data = new int[1];
data[0] = fontNumber;
directIO(SmFptrConst.SMFPTR_DIO_GET_TEXT_LENGTH, data, null);
int textLength = data[0];
```

**Comment by tehreh1uneh** [comment]
Спасибо!
