### ISSUE TITLE
Отмена печати бумажного чека

### ISSUE THREAD

**Issue by tehreh1uneh** [shtrih-m/javapos_shtrih#53]
Добрый день, согласно [примеру](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java), чтобы не печатать бумажный чек, необходимо добавить запись в определенную таблицу. В какую - зависит от того, взаимодействуешь с кассовым ядром или с кассой. В примере кассовое ядро это или нет определяется по модели и ядром считается модель с номером 45. Это не всегда правда, например [POSCenter A7L](https://xn----7sbba6bhdpdf5ba.xn--p1ai/product/poscenter-a7l) возвращает 46 (на новых прошивках), но при этом там как раз кассовое ядро. Есть ли какая-то обертка для отмены печати бумажного чека? Например, в последних версиях C++ драйвера (который на GitLab у вас) добавлено свойство, которое за это отвечает.    Подскажите, как корректно решить проблему в случае изпользования JavaPos драйвера?

**Comment by tehreh1uneh** [comment]
Спасибо!

**Comment by nyxiscoo1** [comment]
Исправил в [545](https://github.com/shtrih-m/javapos_shtrih/releases/tag/545) релизе, так же поправил примеры, добавил некий уровень абстракции для пользователя, что б драйвер сам брал на себя определение модели.
