### ISSUE TITLE
Получить сумму денег в денежном ящике

### ISSUE THREAD

**Issue by tehreh1uneh** [shtrih-m/javapos_shtrih#55]
Добрый день, подскажите, как получить сумму денег в денежном ящике?
В C++ драйвере это позволяет сделать команда `ReadCashDrawerSum()`, здесь не могу разобраться

**Comment by tehreh1uneh** [comment]
`readCashRegister` возвращает объект `CashRegister`, как прочитать значение суммы, используя этот объект?

**Comment by tehreh1uneh** [comment]
При попытке вызова `readCashRegister(241)` возвращается ошибка с сообщением "Нет связи". При этом остальное взаимодействие не нарушено (например, внесение и выдача денег, печать строк и другие операции). Подскажите, куда копать дальше в подобной ситуации?

**Comment by nyxiscoo1** [comment]
> readCashRegister возвращает объект CashRegister, как прочитать значение суммы, используя этот объект? Или же value типа long - это значение суммы, где два последних знака - дробная часть?

Да, value это сумма в копейках.

> При попытке вызова readCashRegister(241) возвращается ошибка с сообщением "Нет связи". 

Это странно. Какое устройство используется? Можете прислать лог с описанной ситуацией?

**Comment by tehreh1uneh** [comment]
Долго не было возможности вернуться к этой проблеме, но теперь ошибка не проявляется. Причину уже найти не смогу, спасибо за помощь.
