### ISSUE TITLE
Выравнивание текста и перенос по словам

### ISSUE THREAD

**Issue by tehreh1uneh** [shtrih-m/javapos_shtrih#61]
Добрый день, 

- есть ли готовое решение для настройки выравнивания текста по центру и по правой стороне?

- есть ли решение для настройки переноса строк по словам, а не посимвольно?

Если нет, то планируется ли?

**Comment by nyxiscoo1** [comment]
Добрый день.

Такого механизма сейчас не существует. Добавлять не планировали.

**Comment by tehreh1uneh** [comment]
Спасибо!
