### ISSUE TITLE
Выбор секции

### ISSUE THREAD

**Issue by JIO6CTEPok** [shtrih-m/javapos_shtrih#62]
Здравствуйте, задаю названия секций:
```
 printer.writeTable(7, 1, 1, "Р/с - наличными");
 printer.writeTable(7, 2, 1, "Р/с - картой");
 printer.writeTable(7, 3, 1, "Спец. счет - наличными");
```
Я так понял - выбор секции - метод setDepartment() в примере - задаю например 2.
`printer.setDepartment(2);`
Вопросы:
1. Как изменить ограничение в 8 символов для названия секций?
2. Почему на чеке отобразились все секции, начиная со второго?
![check](https://user-images.githubusercontent.com/1930971/47837340-bbd9bf80-ddbc-11e8-9fb3-28d153415e76.png)

**Comment by nyxiscoo1** [comment]
Здравствуйте, какое устройство используется для печати?

**Comment by JIO6CTEPok** [comment]
используется штрих мобайл ф
прошивка 1.05

**Comment by nyxiscoo1** [comment]
> Как изменить ограничение в 8 символов для названия секций?

8 символов это ограничение самого устройства. Только если попросить доработать прошивку.

> Почему на чеке отобразились все секции, начиная со второго?

Да, воспроизводится. Это похоже баг устройства.

**Comment by nyxiscoo1** [comment]
Можете сказать версию прошивки Вашего мобайла? Ее можно узнать вот так `printer.readLongPrinterStatus().getFirmwareBuild()`.

**Comment by JIO6CTEPok** [comment]
version:A4
build: 20032
date: 13.12.2017

**Comment by nyxiscoo1** [comment]
Завел баг, говорят это норма и даже ожидаемое поведение.

> если название отдела имеет длину 8 символов. Также будут печататься названия всех отделов по цепочке, пока их длина - 8 символов.

**Comment by JIO6CTEPok** [comment]
Спасибо. Подскажите, где можно отслеживать состояние по этому багу? (или это приватный репозиторий?)

**Comment by nyxiscoo1** [comment]
Это наш внутренний трэкер и обращение уже закрыто, это не баг, а фича и ожидаемое поведение.

**Comment by nyxiscoo1** [comment]
Не смотря на ответ о том, что это нормально поведение в следующей версии буду изменения для секций:

> Поправил в 20042 (еще не выпущена). Длина названия отдела равна кол-ву символов в строке стандартным шрифтом (зависит от прошивки). Для шрифта 1 это 48 символов.

**Comment by JIO6CTEPok** [comment]
Хорошо, спасибо, ждем.
