### ISSUE TITLE
ошибка печати на новой версии

### ISSUE THREAD

**Issue by JIO6CTEPok** [shtrih-m/javapos_shtrih#63]
при печати чека пробую открыть день, если он закрыт и возникает ошибка. мы обновили прошивку на штрих-м в надежде что он поддерживает передачу места расчета(я раннее создавал вопрос). в последней прошивне не открывается день.
 скришнот стектрейса:
https://imgur.com/KPEaixa
версия прошивки:
Версия ПО                 : A.4
 Сборка ПО                 : 20041
 Дата ПО                   : 16.10.2018

**Comment by nyxiscoo1** [comment]
Добрый день! 
У меня этой версии нет, проверить не могу сам.
Можете дать лог драйвера?

**Comment by JIO6CTEPok** [comment]
Что-то намутили с прошивками, накатили еще раз - проблема пропала.
