### ISSUE TITLE
51. Некорректные параметры в команде

### ISSUE THREAD

**Issue by JIO6CTEPok** [shtrih-m/javapos_shtrih#64]
Обновили в очередной раз прошивку принтера в надежде распечатать успешно чек. Последние проблемы с печатью тегов в целом. Уменьшили количество тегов для тестирования, но все равно не печатается, возникает ошибка при вызове функции endFiscalReceipt(false).

firmware revision:A4, 20041, 16.10.2018

> 23:01:11.783 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - beginFiscalReceipt: OK
> 23:01:11.785 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@30a18fad, 6666666666)
> 23:01:11.805 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.807 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@3b5f12e2, 5252600224  )
> 23:01:11.809 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.810 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@3c081673, тест адреса)
> 23:01:11.812 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.813 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@163ac930, тест адреса)
> 23:01:11.815 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.816 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@2b7479a9, 89524620857)
> 23:01:11.819 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.820 [RxNewThreadScheduler-2] DEBUG r.c.a.p.m.i.r.PrinterManager - print products
> 23:01:11.822 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(18, [I@3f5f7b2e, [Ljava.lang.String;@6c3a6cf)
> 23:01:11.823 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.826 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO(18, [I@113b485c, [Ljava.lang.String;@39720765)
> 23:01:11.827 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 23:01:11.829 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - printRecItem(Почтово-курьерские услуги, 0, 1000, 1, 6500000, )
> 23:01:11.831 [RxNewThreadScheduler-2] DEBUG c.s.j.f.receipt.FSSalesReceipt - price: 0, quantity: 1000, unitPrice: 6500000
> 23:01:11.834 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - printRecItem: OK
> 23:01:11.836 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - printRecTotal(0, 6500000, 0)
> 23:01:11.837 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterImpl - printRecTotal
> 23:01:11.839 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - printRecTotal: OK
> 23:01:11.841 [RxNewThreadScheduler-2] DEBUG r.c.a.p.m.i.r.PrinterManager - setSuspended
> 23:01:11.843 [RxNewThreadScheduler-2] DEBUG r.c.a.p.m.i.r.PrinterManager - endFiscalReceipt
> 23:01:11.844 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterService - endFiscalReceipt(false)
> 23:01:11.845 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterImpl - endFiscalReceipt
> 23:01:11.848 [RxNewThreadScheduler-2] DEBUG c.s.f.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status
> 23:01:11.849 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 08 00 BA 00 FF 01 1E 00 00 00 40 C6
> 23:01:11.930 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 23 00
> 23:01:11.931 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- BA 00
> 23:01:11.934 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 01 00 03 04 01 01 00 12 0B 08 16 21 39 39 39 39 30 37 38
> 23:01:11.935 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 39 30 32 30 30 31 31 31 32 6D 00 00 00
> 23:01:11.936 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 6A DC
> 23:01:11.938 [RxNewThreadScheduler-2] DEBUG c.s.f.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status = 0, 90 ms
> 23:01:11.940 [RxNewThreadScheduler-2] DEBUG c.s.f.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data
> 23:01:11.941 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 16 00 BB 00 FF 0C 1E 00 00 00 A8 04 0A 00 36 36 36 36 36
> 23:01:11.942 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 36 36 36 36 36 01 8D
> 23:01:12.030 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 05 00
> 23:01:12.031 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- BB 00
> 23:01:12.033 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 0C 33
> 23:01:12.035 [RxNewThreadScheduler-2] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 96 C6
> 23:01:12.036 [RxNewThreadScheduler-2] ERROR c.s.f.SMFiscalPrinterImpl - 51, Некорректные параметры в команде, FF0C1E000000A8040A0036363636363636363636
> 23:01:12.037 [RxNewThreadScheduler-2] DEBUG c.s.j.f.FiscalPrinterImpl - ErrorEvent(JPOS_E_EXTENDED, 351)
> 23:01:12.039 [RxNewThreadScheduler-2] DEBUG c.s.f.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data = 51, 100 ms
> 23:01:12.041 [RxNewThreadScheduler-2] ERROR c.s.j.f.JposExceptionHandler - JposException. ErrorCode: 114, ErrorCodeExtended: 351, '51, Некорректные параметры в команде'
> 23:01:12.080 [RxNewThreadScheduler-2] ERROR r.c.a.p.m.i.r.PrintReceiptSuccessInteractor - print receipt error
> jpos.JposException: 51, Некорректные параметры в команде
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:83)
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:456)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:39)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1533)
> 	at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817)
> 	at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.endFiscalReceipt(ShtrihFiscalPrinter113.java:707)
> 	at ru.cdc.android.ponyexpress.data.impl.receiptprint.shtrihmobile.ShtrihPrinterManager.lambda$printReceipt$13$ShtrihPrinterManager(ShtrihPrinterManager.java:364)

**Comment by nyxiscoo1** [comment]
Я не вижу никаких проблем в приведенных байтах, все отправляется в соответствии с протоколом.

В описании прошивки 20040 есть такой пункт:

> 4. Команды FF0C и FF4D принимают в обработку теги с проверкой длины TLV и ФЛК: 1005, 1008, 1009, 1016, 1021, 1026, 1044, 1046, 1048, 1057, 1060, 1073, 1074, 1075, 1117, 1126, 1171, 1177, 1178, 1179, 1187, 1193, 1203, 1207, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231.Передача осуществляется только тех тегов, которые могут быть переданы в текущий открытый документ ФН.

> 9. В команду FF45 Закрытия чека V2 добавлены загружаемые (проверяемые) теги:ЭФ: 1203, 1008, 1117, 1227, 1228, 1057, 1075, 1044, 1073, 1074, 1026, 1005, 1016, 1171, 1009, 1187.ПФ (по настройке автопечати): 1117, 1008, 1009, 1187, 1227, 1228, 1057, 1075, 1044, 1073, 1074, 1026, 1005, 1016, 1171.

Они меня настораживают, т.к. тэга 1192, который передается Вами я тут не вижу.
Завтра обновлю свой мобайл, проверю сам + задал вопрос разработчику жду ответа.

Если передача тэга 1192 запрещена на уровне прошивки, то возможно поможет отключение ФЛК

> 1. Добавлены поля в табл.1:41: "TLV ФЛК, 0-ВЫКЛ, 1-ВКЛ" (по умолчанию, 1) - режим форматно-логического контроля значений в передаваемых тегах;

**Comment by JIO6CTEPok** [comment]
флк выключили(printer.writeTable(1, 1, 41, "0");)
все также

**Comment by JIO6CTEPok** [comment]
а передача в офд?

**Comment by nyxiscoo1** [comment]
Какая передача в ОФД, не совсем понял вопрос.

**Comment by JIO6CTEPok** [comment]
т.е. тег 1192 не поддерживается никак, и требование о передаче тега 1192 в офд не выполняется на уровне прошивки?

**Comment by JIO6CTEPok** [comment]
пересмотрел док, действительно, 1192 не обязателен к передаче в офд.

**Comment by iboxmpos** [comment]
Коллеги, привет! Да, не обязателен, но ФНС настойчиво рекомендует указывать в данном ТЕГе при совершении Возврата прихода ФПД чека Прихода. Исходя из практики такая рекомендации в скором времени превратится в обязательную процедуру и придется снова переделывать интеграцию.

**Comment by serovpetr** [comment]
Привет. 
Коллеги, немного дополню основное обращение. Проблема в том, что на прошивке 20041 печать отваливается при передаче вообще любого тега, не только 1192. 
Прошивка 20032 печатает тот же чек без ошибки.

**Comment by nyxiscoo1** [comment]
Доброго дня, коллеги!

> Коллеги, немного дополню основное обращение. Проблема в том, что на прошивке 20041 печать отваливается при передаче вообще любого тега, не только 1192.

Мне прошили Мобайл на 20041, посмотрю в ближайшее время, но в любом случае в такие обращения лучше прикладывать лог.

**Comment by nyxiscoo1** [comment]
@serovpetr у меня работает передача тэгов. Можете прислать лог с ошибкой?

**Comment by goldenluk** [comment]
Присоединюсь к проблеме. Та же самая ситуация на прошивке 20041.
Тег 1192 не передаю.
Вот последнее что есть в логах:
E/com.shtrih.fiscalprinter.SMFiscalPrinterImpl: 51, Некорректные параметры в команде, FF0C1E00000031040F00382D3830302D312D3030302D303030
D/com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl: ErrorEvent(JPOS_E_EXTENDED, 351)
D/com.shtrih.fiscalprinter.SMFiscalPrinterImpl: FF0Ch, Fiscal storage: write TLV data = 51, 114 ms
E/com.shtrih.jpos.fiscalprinter.JposExceptionHandler: JposException. ErrorCode: 114, ErrorCodeExtended: 351, '51, Некорректные параметры в команде'
D/com.shtrih.jpos.fiscalprinter.FiscalPrinterService: close()
D/com.shtrih.jpos.fiscalprinter.FiscalPrinterService: close: OK

**Comment by nyxiscoo1** [comment]
> FF0C1E00000031040F00382D3830302D312D3030302D303030

@goldenluk скорее всего не проходит ФЛК, насколько я могу судить по первому символу 38 это не + как требуется по ФФД.

![image](https://user-images.githubusercontent.com/284666/48480108-610f8180-e81a-11e8-8c4f-bb328a89672b.png)

**Comment by goldenluk** [comment]
> 
> 
> > FF0C1E00000031040F00382D3830302D312D3030302D303030
> 
> @goldenluk скорее всего не проходит ФЛК, насколько я могу судить по первому символу 38 это не + как требуется по ФФД.
> 
> ![image](https://user-images.githubusercontent.com/284666/48480108-610f8180-e81a-11e8-8c4f-bb328a89672b.png)

Проверил, вот такие вот теги передаются
![default](https://user-images.githubusercontent.com/25905825/48543969-36dec200-e8f5-11e8-8461-6968162eb307.png)

Пробовал в 1073 передать строку начинающуюся с + и состоящую только из цифр (например 
+79999328734), такая же ошибка

**Comment by nyxiscoo1** [comment]
Я сейчас проверил у меня не валидируется формат телефона даже при включенном ФЛК.
Можете прислать пример кода, либо полный лог, я попробую воспроизвести на своем устройстве.

**Comment by JIO6CTEPok** [comment]
в общем, печать завелась кое-как.
Что сделали:
1. вместо печати тега 1187 передаем значение в таблицу:
`printer.writeTable(14, 1, 14, property.getValue());`
2. отключили печать 1192

**Comment by nyxiscoo1** [comment]
> вместо печати тега 1187 передаем значение в таблицу:
> printer.writeTable(14, 1, 14, property.getValue());

Передача места и адреса расчетов работает в режиме развозной торговли, то Вы делаете похоже на некий хак.

> отключили печать 1192

Можно печатать в 20043, мне пришла рассылка о ее релизе вчера.

**Comment by JIO6CTEPok** [comment]
> Передача места и адреса расчетов работает в режиме развозной торговли, то Вы делаете похоже на некий хак.
О, перерегистрация под режим развозной торговли решила этот пункт. Спасибо.

**Comment by goldenluk** [comment]
> 
> 
> Я сейчас проверил у меня не валидируется формат телефона даже при включенном ФЛК.
> Можете прислать пример кода, либо полный лог, я попробую воспроизвести на своем устройстве.

Вот кусок кода, развернул некоторые методы и поменял значения некоторые на magic const, чтобы было понятно.
На этом коде получаю такую же ошибку

        final int fiscalReceiptType = FiscalPrinterConst.FPTR_RT_SALES;
        
        printer.setFiscalReceiptType(fiscalReceiptType);

        printer.beginFiscalReceipt(true);


        //writePaymentTags(receipt.getTags());
        //Развернул сожержимое метода, чтобы было понятно, какие теги передаём
        printer.fsWriteTag(1016, "2225031594  ");
        printer.fsWriteTag(1073, "+7-800-1-000-000");
        printer.fsWriteTag(1057, "1");
        printer.fsWriteTag(1005, "НОВОСИБИРСК,КИРОВА,86");
        printer.fsWriteTag(1075, "+7(383) 335-80-88");
        printer.fsWriteTag(1171, "+7(383)339-92-42");
        printer.fsWriteTag(1044, "Прием денежных средств");
        printer.fsWriteTag(1026, "РНКО \"ПЛАТЕЖНЫЙ ЦЕНТР\"");

        //receipt.getReceipt() - текст чека типа String
        printer.printNormal(FiscalPrinterConst.FPTR_S_RECEIPT, receipt.getReceipt());

        final String unitName = receipt.getType() == Receipt.Type.SELL ? "Оплата" : "Возврат";

        printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_PAYMENT_TYPE, 4);
        printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_SUBJECT_TYPE, 4);

        if (fiscalReceiptType == FiscalPrinterConst.FPTR_RT_SALES) {
            printer.printRecItem("Приём платежа", 12300, 0, 0, 0, unitName);

            printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_PAYMENT_TYPE, 4);
            printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_SUBJECT_TYPE, 4);

            printer.printRecItem("Размер вознаграждения", 123, 0, 3, 0, unitName);
        } else {
            printer.printRecItemRefund("Приём платежа", receipt.getTotalSum() - receipt.getCommissionSum(), 0, 0, 0, unitName);

            printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_PAYMENT_TYPE, receipt.getMethodTypeCommiss());
            printer.setParameter(SmFptrConst.SMFPTR_DIO_PARAM_ITEM_SUBJECT_TYPE, receipt.getSubjectTypeCommiss());

            printer.printRecItemRefund("Размер вознаграждения", receipt.getCommissionSum(), 0, receipt.getVatInfo(), 0, unitName);
        }
        printer.printRecTotal(12423, 12423, "0");
        printer.endFiscalReceipt(false);

**Comment by nyxiscoo1** [comment]
Указанные данные не соответствуют ФФД и я думаю, что не проходят ФЛК добавленный в 20041 прошивке .

```Java
printer.fsWriteTag(1016, "2225031594  ");
printer.fsWriteTag(1073, "+78001000000");
printer.fsWriteTag(1057, "1");
printer.fsWriteTag(1005, "НОВОСИБИРСК,КИРОВА,86");
printer.fsWriteTag(1075, "+73833358088");
printer.fsWriteTag(1171, "+73833399242");
printer.fsWriteTag(1044, "Прием денежных средств");
printer.fsWriteTag(1026, "РНКО \"ПЛАТЕЖНЫЙ ЦЕНТР\"");
```

С такими тэгами проблем не возникает.

**Comment by nyxiscoo1** [comment]
Это проблема не в драйвере, смотрите тикет #65.

**Comment by goldenluk** [comment]
> 
> 
> Это проблема не в драйвере, смотрите тикет #65.

Спасибо, ознакомимся
