### ISSUE TITLE
185, Сигнатура версии структуры данных в накопителе не совпадает с текущей версией ПО

### ISSUE THREAD

**Issue by JIO6CTEPok** [shtrih-m/javapos_shtrih#65]
Здравствуйте. Реализовали "Продажу" и "Возврат" основных чеков (Курьерская доставка магазинных товаров).
Также необходимо реализовать продажу и возврат по "свободному чеку".
Для свободного чека "продажа" выполняется корректно.
Предварительно указав инн курьера в "продажу" свободного чека передаем теги 1009, 1187, 1008(если имеется значение), а также одну позицию "Почтово-курьерские услуги" 1212=Услуга

Возврат для свободного чека не работает - возникает ошибка 185. Сигнатура версии структуры данных в накопителе не совпадает с текущей версией ПО.

Подскажите, проблема в нехватке тегов, или где-то еще? Не можем разобраться.

<details><summary>log</summary>
<p>

> 17:39:28.904 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - beginFiscalReceipt: OK
> 17:39:28.905 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO(52, [I@1ed77756, 098227043272)
> 17:39:28.907 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 17:39:28.909 [RxNewThreadScheduler-9] DEBUG r.c.a.p.m.i.r.PrinterManager - print products
> 17:39:28.910 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO(18, [I@2a9e33d7, [Ljava.lang.String;@871c4c4)
> 17:39:28.911 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 17:39:28.912 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO(18, [I@35fcafad, [Ljava.lang.String;@6ebb2e2)
> 17:39:28.913 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - directIO: OK
> 17:39:28.915 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - printRecItemRefund(Почтово-курьерские услуги, 0, 1000, 1, 654000, )
> 17:39:28.916 [RxNewThreadScheduler-9] DEBUG c.s.j.f.receipt.FSSalesReceipt - price: 0, quantity: 1000, unitPrice: 654000
> 17:39:28.917 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - printRecItemRefund: OK
> 17:39:28.919 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - printRecTotal(0, 654000, 1)
> 17:39:28.919 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterImpl - printRecTotal
> 17:39:28.920 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - printRecTotal: OK
> 17:39:28.921 [RxNewThreadScheduler-9] DEBUG r.c.a.p.m.i.r.PrinterManager - setSuspended
> 17:39:28.922 [RxNewThreadScheduler-9] DEBUG r.c.a.p.m.i.r.PrinterManager - endFiscalReceipt
> 17:39:28.923 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterService - endFiscalReceipt(false)
> 17:39:28.924 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterImpl - endFiscalReceipt
> 17:39:28.925 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status
> 17:39:28.926 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 08 00 1D 02 FF 01 1E 00 00 00 52 E7
> 17:39:29.008 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 23 00
> 17:39:29.009 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 1D 02
> 17:39:29.011 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 01 00 03 04 01 01 00 12 0B 0F 11 26 39 39 39 39 30 37 38
> 17:39:29.012 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 39 30 32 30 30 31 31 31 32 A5 00 00 00
> 17:39:29.014 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- E9 6F
> 17:39:29.015 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status = 0, 90 ms
> 17:39:29.016 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data
> 17:39:29.017 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 18 00 1E 02 FF 0C 1E 00 00 00 B3 04 0C 00 30 39 38 32 32
> 17:39:29.018 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 37 30 34 33 32 37 32 43 74
> 17:39:29.108 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 05 00
> 17:39:29.110 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 1E 02
> 17:39:29.111 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 0C 00
> 17:39:29.112 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FD 24
> 17:39:29.114 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data = 0, 98 ms
> 17:39:29.115 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - printVoidSale
> 17:39:29.117 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF46h, FS: Print receipt item
> 17:39:29.118 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 4A 00 1F 02 FF 46 01 00 00 00 02 40 42 0F 00 00 00 B0 FA
> 17:39:29.120 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 09 00 00 B0 FA 09 00 00 FF FF FF FF FF 01 01 04 04 CF EE F7
> 17:39:29.121 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> F2 EE E2 EE 2D EA F3 F0 FC E5 F0 F1 EA E8 E5 20 F3 F1 EB F3
> 17:39:29.122 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> E3 E8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C6 2A
> 17:39:29.238 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 05 00
> 17:39:29.239 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 1F 02
> 17:39:29.241 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 46 00
> 17:39:29.242 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- AB 6C
> 17:39:29.256 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF46h, FS: Print receipt item = 0, 139 ms
> 17:39:29.258 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF45h, Fiscal storage: close receipt
> 17:39:29.259 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - getSubtotal
> 17:39:29.260 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - 89h, Get receipt subtotal
> 17:39:29.261 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 07 00 20 02 89 01 00 00 00 77 B0
> 17:39:29.294 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 0A 00
> 17:39:29.296 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 20 02
> 17:39:29.299 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 89 00 01 B0 FA 09 00 00
> 17:39:29.301 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- B0 C0
> 17:39:29.302 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - 89h, Get receipt subtotal = 0, 42 ms
> 17:39:29.304 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 8F 78 00 21 02 FF 45 01 00 00 00 00 00 00 00 00 B0 FA 09 00
> 17:39:29.305 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 17:39:29.307 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 17:39:29.308 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 17:39:29.309 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 17:39:29.310 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 17:39:29.312 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - -> 00 00 00 A3 95
> 17:39:29.419 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 05 00
> 17:39:29.420 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 21 02
> 17:39:29.421 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- FF 45 B9
> 17:39:29.422 [RxNewThreadScheduler-9] DEBUG c.s.fiscalprinter.PrinterProtocol_2 - <- 4C CC
> 17:39:29.423 [RxNewThreadScheduler-9] ERROR c.s.f.SMFiscalPrinterImpl - 185, Сигнатура версии структуры данных в накопителе не совпадает с текущей версией ПО, FF45010000000000000000B0FA090000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> 17:39:29.424 [RxNewThreadScheduler-9] DEBUG c.s.j.f.FiscalPrinterImpl - ErrorEvent(JPOS_E_EXTENDED, 485)
> 17:39:29.426 [RxNewThreadScheduler-9] DEBUG c.s.f.SMFiscalPrinterImpl - FF45h, Fiscal storage: close receipt = 185, 169 ms
> 17:39:29.427 [RxNewThreadScheduler-9] ERROR c.s.j.f.JposExceptionHandler - JposException. ErrorCode: 114, ErrorCodeExtended: 485, '185, Сигнатура версии структуры данных в накопителе не совпадает с текущей версией ПО'
> 17:39:29.447 [RxNewThreadScheduler-9] ERROR r.c.a.p.m.i.r.PrintReceiptSuccessInteractor - print receipt error
> jpos.JposException: 185, Сигнатура версии структуры данных в накопителе не совпадает с текущей версией ПО
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposExceptionWithoutDetails(JposExceptionHandler.java:83)
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.getJposException(JposExceptionHandler.java:52)
> 	at com.shtrih.jpos.fiscalprinter.JposExceptionHandler.handleException(JposExceptionHandler.java:41)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl.handleException(FiscalPrinterImpl.java:456)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.handleException(FiscalPrinterService.java:39)
> 	at com.shtrih.jpos.fiscalprinter.FiscalPrinterService.endFiscalReceipt(FiscalPrinterService.java:1533)
> 	at jpos.FiscalPrinter.endFiscalReceipt(FiscalPrinter.java:3817)
> 	at com.shtrih.fiscalprinter.ShtrihFiscalPrinter113.endFiscalReceipt(ShtrihFiscalPrinter113.java:707)
> 

</p>
</details>

ШТРИХ-МОБАЙЛ-Ф, 8506, ПО ФР: A4.20041

**Comment by nyxiscoo1** [comment]
Здравствуйте, мне на этой неделе писали о похожей проблеме. Люди решили так:
> Удалось восстановить работоспособность ККТ, проблема решилась полным сбросом с перерегистрацией.

Это проблема не в драйвере, а в устройстве, рекомендую обратиться в техподдержку.

**Comment by JIO6CTEPok** [comment]
попробуем, конечно. Вообще ситуация воспроизводится более чем на одном принтере...

**Comment by nyxiscoo1** [comment]
100% в техподдержку нужно обратиться, мб это баг в новой прошивке.

**Comment by JIO6CTEPok** [comment]
в общем, добавили в чек возврата адрес покупателя и место оплаты, и возват свободного чека завелся.
