### ISSUE TITLE
tag 1203

### ISSUE THREAD

**Issue by dazre** [shtrih-m/javapos_shtrih#71]
Приветствую!

При попытке прописать тег 1203 сразу после FSStartDayOpen вылезает ошибка:

DEBUG com.shtrih.jpos.fiscalprinter.FiscalPrinterService - directIO(SMFPTR_DIO_FS_WRITE_TAG, [I@1761e840, 1234567890  )
DEBUG com.shtrih.fiscalprinter.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - sendCommand: Fiscal storage: read status, false
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 05
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 15
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 02 06 FF 01 1E 00 00 00 E6
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 06
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 02
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 21
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- FF 01 00 03 02 00 00 00 13 02 1A 12 0D 39 39 39 39 30 37 38
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 39 30 30 30 30 37 39 30 33 88 00 00 00 49
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 06
DEBUG com.shtrih.fiscalprinter.SMFiscalPrinterImpl - FF01h, Fiscal storage: read status = 0, 93 ms
DEBUG com.shtrih.fiscalprinter.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - sendCommand: Fiscal storage: write TLV data, false
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 05
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 15
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 02 16 FF 0C 1E 00 00 00 B3 04 0C 00 31 32 33 34 35 36 37 38
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 39 30 20 20 41
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 06
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 02
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- 03
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - <- FF 0C 33 C3
DEBUG com.shtrih.fiscalprinter.PrinterProtocol_1 - -> 06
ERROR com.shtrih.fiscalprinter.SMFiscalPrinterImpl - 51, Некорректные параметры в команде, FF0C1E000000B3040C00313233343536373839302020
DEBUG com.shtrih.jpos.fiscalprinter.FiscalPrinterImpl - ErrorEvent(JPOS_E_EXTENDED, 351)
DEBUG com.shtrih.fiscalprinter.SMFiscalPrinterImpl - FF0Ch, Fiscal storage: write TLV data = 51, 47 ms
ERROR com.shtrih.jpos.fiscalprinter.JposExceptionHandler - JposException. ErrorCode: 114, ErrorCodeExtended: 351, '51, Некорректные параметры в команде'

Operator number                : 1
Printer firmware version       : C1, 60325, 24.10.2018
Printer store number           : 1
Document number                : 139
Printer mode                   : 4, 4, Day is closed
Printer submode                : 0, 0, Paper is present
Printer internal port number   : 3
FM firmware                    : N.A.0, 01.01.2016
Printer date and time          : 27.02.2019, 13:34:08
Serial number                  : 67890
Day number                     : 30
FM free records                : 0
Registration number            : 0
Fiscalizations left            : 0
Fiscal ID                      : 7734251515

Device type                    : 0.0
Protocol version               : 1.14
Model ID                       : 250
Device language                : 0
Device name                    : ШТРИХ-М-02Ф

**Comment by nyxiscoo1** [comment]
Добрый день!

Это странно, можно более полный лог? С началом открытия смены.
И скажите, пожалуйста, версию драйвера.

**Comment by dazre** [comment]
[shtrihjavapos.log](https://github.com/shtrih-m/javapos_shtrih/files/2910415/shtrihjavapos.log)

Версия драйвера - у меня версия из master-а.

**Comment by nyxiscoo1** [comment]
Рабочая теория такова, что 1234567890 не является валидным ИНН, устройство его проверяет.
Попробуйте задать настоящий ИНН, либо отключить ФЛК.

**Comment by dazre** [comment]
Действительно. При валидном ИНН запись прошла успешно. Спасибо!
