### ISSUE TITLE
Как узнать, что кассовая смена превысила 24 часа?

### ISSUE THREAD

**Issue by Agrassx** [shtrih-m/javapos_shtrih#72]
Здравствуйте,  попробовал `ShtrihFiscalPrinter.readLongPrinterStatus().getSubmode() == SmFptrConst.SMFPTR_DAY_STATUS_EXPIRED` Возвращает false. Попробовал еще всякие методы которые возвращают состояние - результат тот же. Смена точно превысила 24ч, ККТ жалуется при попытке напечатать чек. Подскажите, пожалуйста, как мне узнать это до попытки напечатать чек?

**Comment by Agrassx** [comment]
`ShtrihFiscalPrinter.readDayStatus() == SMFPTR_DAY_STATUS_EXPIRED` Нашел метод, это правильный метод?

**Comment by nyxiscoo1** [comment]
Добрый день, определить истекла ли смена можно запросив режим ФР, он должн быть 3

**Comment by Agrassx** [comment]
Спасибо, особенно за нюанс с про остальные ККТ :)
