### ISSUE TITLE
Отсутствует фискальный признак последнего ФД при чтении состояния ФН

### ISSUE THREAD

**Issue by zTrap** [shtrih-m/javapos_shtrih#73]
В листе не возвращается данный параметр https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/Core/src/com/shtrih/jpos/fiscalprinter/directIO/DIOReadFSParams.java#L51

**Comment by VitalyKravtsov2016** [comment]
Сейчас поправим. Я сделаю новый directIO, чтобы оставить совместимость.

**Comment by VitalyKravtsov2016** [comment]
[+] Добавлена команда directIO(SMFPTR_DIO_READ_FS_PARAMS2) для чтения параметров ФН
https://github.com/shtrih-m/javapos_shtrih/releases/tag/570
