### ISSUE TITLE
printZReport: 51, Некорректные параметры в команде, 

### ISSUE THREAD

**Issue by dazre** [shtrih-m/javapos_shtrih#74]
Добрый день!

Вылезла ошибка на закрытии смены.

[shtrihjavapos.log](https://github.com/shtrih-m/javapos_shtrih/files/2965875/shtrihjavapos.log)
версия драйвера соотв. коммиту https://github.com/shtrih-m/javapos_shtrih/commit/789cb2674e099784376dcc674a9e704f68b821da

**Comment by nyxiscoo1** [comment]
Добрый день!

Это странно, указанная последовательность команд должна работать. Дело не в драйвере.

Эта ошибка постоянно повторяется?

**Comment by dazre** [comment]
Собственно потому и написал. Вчера все операции работали, а сегодня на тебе... А это может быть связано с тем, что ФД не отправляются в ОФД?

**Comment by nyxiscoo1** [comment]
Обычно там другая ошибка, что-то типа Исчерпан ресурс ФН.
Но если есть документы старше 30 дней, то да, ККТ не должна работать.

Обновлялся ли драйвер со вчера? Если да, то откат к старой версии помогает?

**Comment by dazre** [comment]
старше 30 дней документов точно нет. Драйвер не обновлялся.

**Comment by nyxiscoo1** [comment]
Тут я не знаю чем помочь, на моих кассах такого не воспроизводится. Мб это баг в прошивке, обратитесь в техподдержку по кассам.

**Comment by dazre** [comment]
Хорошо. Спасибо!

**Comment by dazre** [comment]
Ошибка постоянно воспроизводится в следующей последовательности:
1. запуск драйвера (запускаем программу),
2. открытие смены,
3. остановка драйвера (закрываем программу),
4. пытаемся закрыть смену.

Если все операции от открытия до закрытия смена проводятся в процессе одного запуска драйвера, ошибки нет.

В приложении лог с демонстрацией ошибки.
[shtrihjavapos.log](https://github.com/shtrih-m/javapos_shtrih/files/3098326/shtrihjavapos.log)

**Comment by nyxiscoo1** [comment]
Добрый день.
Проанализировал лог: могу предположить, что к наблюдаемому поведению может приводить запись пустой строки в имя кассира. 
Попробуйте записать туда непустую строку и повторить эксперимент.

**Comment by dazre** [comment]
Действительно, после перезапуска драйвера имя кассира (которое задается на открытии смены) равно пустой строке. Если его сделать не пустым или просто не вызывать команду записи имени кассира, драйвер работает корректно.

Спасибо!
