### ISSUE TITLE
Каким образом получить процент заряда

### ISSUE THREAD

**Issue by zTrap** [shtrih-m/javapos_shtrih#75]
Как можно получить точный процент заряда?

**Comment by nyxiscoo1** [comment]
Добрый день!
Что б считать процент заряда в устройстве должна быть определенная микросхема.
Насколько мне известно ни на одном из устройств ее нет.
Если речь идет о ШТРИХ-МОБАЙЛ-Ф, то в issue #30 описан способ рассчитать двухуровневую индикацию.
