### ISSUE TITLE
Ошибка при выплате денег

### ISSUE THREAD

**Issue by Stachel** [shtrih-m/javapos_shtrih#78]
Добрый день.

В последней версии драйвера при выплате денег 
```
printer.setFiscalReceiptType(FPTR_RT_CASH_OUT);
printer.beginFiscalReceipt(false);
printer.printRecCash(sum);
printer.printRecTotal(sum, sum, "0");
printer.endFiscalReceipt(false);
```

Если в кассе недостаточно средств метод endFiscalReceipt() выдает ошибку 
115 - Команда не поддерживается в данном режиме

В старой версии драйвера была ошибка "Не хватает наличности в кассе". Сейчас как-то можно узнать по какой именно причине не прошла операция?

**Comment by nyxiscoo1** [comment]
Добрый день.

Производился ли сброс состояния принтера перед попыткой произвести выплату?

В данной ситуации очень бы помог лог.

**Comment by Stachel** [comment]
Нет, сброс состояния не делался.

Вывод Logcat: [LogOutMoney.txt](https://github.com/shtrih-m/javapos_shtrih/files/3094426/LogOutMoney.txt)

При этом меньшая сумма корректно обрабатывается и печатается чек о выплате наличных.

**Comment by nyxiscoo1** [comment]
Да, это баг. Исправим.

**Comment by Stachel** [comment]
Подскажите, пожалуйста, а в какой версии будет исправлена ошибка?

**Comment by nyxiscoo1** [comment]
В [575](https://github.com/shtrih-m/javapos_shtrih/releases/tag/575) должно быть исправлено.

**Comment by Stachel** [comment]
Спасибо! Заработало )
