### ISSUE TITLE
Штрих нано. Задание тегов

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/javapos_shtrih#85]
Здравствуйте. Мне нужно задать следующие значения в чеке продажи и возврата:
Признак агента;
Наименование поставщика;
Телефон поставщика;
ИНН поставщика.
Могу ли я воспользоваться для этого соответствующими тегами:
1222;
1225;
1171;
1226?
Если могу, после/до каких инструкций?
Я пыталась записать теги до printRecItem и после него, но получала ошибку 111

**Comment by nyxiscoo1** [comment]
Здравствуйте.
Указанные тэги входят в предмет расчета, соответственно их нужно писать до или после printRecItem в зависимости от модели устройства [вот код](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L233) определяющий нужно ли писать привязанные к операции тэги до или после.
Плюс нужно учитывать, что тэги 1171 и 1225 должны быть обернуты в тэг [1224 перед отправкой](https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L270).
А при записи признака агента ККТ должна быть заругистрирована с соответствующим признаком.

Если вышеописанные советы не помогут, то желательно иметь описание ошибки и лог.

**Comment by ola-skorp** [comment]
Признак агента, наименование поставщика и телефон поставщика записать вроде удалось. Остался ИНН. Передаю его строкой в fsWriteOperationTag в тег 1226 и получаю следующую ошибку:
jpos.JposException: 51, Некорректные параметры в команде

**Comment by nyxiscoo1** [comment]
Нужно убедиться. что это правильный ИНН.
Если не поможет напишите какой передаете и прикрепите лог.

**Comment by ola-skorp** [comment]
printer.fsWriteOperationTag(1226, "7734384850")
https://gist.github.com/ola-skorp/48798d24b99549a9c4006bf04f4cfad8

**Comment by nyxiscoo1** [comment]
ИНН не дополнен пробелами до (12 символов)[https://github.com/shtrih-m/javapos_shtrih/blob/master/Source/android/tinyJavaPosTester/src/com/shtrih/tinyjavapostester/FFD105Documents.java#L476].

**Comment by ola-skorp** [comment]
Спасибо
