### ISSUE TITLE
Не билдится проект

### ISSUE THREAD

**Issue by Alexander-Iv** [shtrih-m/javapos_shtrih#87]
Добрый день.

Пытаюсь выполнить команду ./gradlew build в каталоге Source. 
Не находит класс SerialPrinterPortSingle

Получаю ошибку:
`:FiscalPrinterService:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\IdeaProjects\javapos_shtrih\Source\Core\src\com\shtrih\fiscalprinter\port\SerialPrinterPort.java:20: error: cannot find symbol
    public SerialPrinterPortSingle port = null;
           ^
  symbol:   class SerialPrinterPortSingle
  location: class SerialPrinterPort
C:\IdeaProjects\javapos_shtrih\Source\Core\src\com\shtrih\fiscalprinter\port\PrinterPortFactory.java:42: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                result = (PrinterPort) ctor.newInstance(parameters);
                                                        ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
C:\IdeaProjects\javapos_shtrih\Source\Core\src\com\shtrih\fiscalprinter\port\SerialPrinterPort.java:26: error: cannot find symbol
        port = SerialPrinterPortSingle.getInstance(portName);
               ^
  symbol:   variable SerialPrinterPortSingle
  location: class SerialPrinterPort
C:\IdeaProjects\javapos_shtrih\Source\Core\src\com\shtrih\fiscalprinter\port\SerialPrinterPort.java:64: error: cannot find symbol
            port = SerialPrinterPortSingle.getInstance(portName);
                   ^
  symbol:   variable SerialPrinterPortSingle
  location: class SerialPrinterPort
`

**Comment by VitalyKravtsov2016** [comment]
Поправил

**Comment by Alexander-Iv** [comment]
Билд выполнился успешно
