### ISSUE TITLE
Как сделать чек отмены?

### ISSUE THREAD

**Issue by battleda** [shtrih-m/javapos_shtrih#89]
Добрый день!
Не нашел в документации как отменить чек, напечатанный в течении смены. Существует метод с параметром [идентификатор чека] для печати чека отмены?

**Comment by nyxiscoo1** [comment]
Добрый день!
Нет, подобного метода не существует. Я так понимаю Вам нужен чек возврата, как его напечатать в примере отражено. Номер оригинального чека возможно нужно записывать в один из тэгов чека, но это не точно.

**Comment by battleda** [comment]
Для отмены чека в открытой смене необходимо использовать чек возврата. О номере оригинального чека в чеке отмене информации не нашел (это не значит, что информации нет).

Спасибо за консультацию!
