### ISSUE TITLE
Номера денежных регистров для безналичных денег 

### ISSUE THREAD

**Issue by battleda** [shtrih-m/javapos_shtrih#92]
Добрый день!

Для получение суммы наличных денег в кассовом ящике я использую метод printer.readCashRegister(241).getValue()

Какие регистры используются для безналичного учета? Есть возможность предоставить регистры и их описание или методы для получения данной информации из ККМ?

**Comment by nyxiscoo1** [comment]
Добрый день.
Вот список регистров: [регистры.txt](https://github.com/shtrih-m/javapos_shtrih/files/3333898/default.txt).
> Какие регистры используются для безналичного учета?  

Не могу с ходу сказать, попробуйте определить по списку. Либо обратитесь в техподдержку по ККТ.

**Comment by battleda** [comment]
В моем случае для расчета продаж по безналичному расчету используются следующие денежные регистры:
Денежный регистр 197                  : Накопление оплат продаж видом оплаты 2 в смене
Денежный регистр 198                  : Накопление оплат покупок видом оплаты 2 в смене
Денежный регистр 199                  : Накопление оплат возврата продаж видом оплаты 2 в смене
Денежный регистр 200                  : Накопление оплат возврата покупок видом оплаты 2 в смене
