### ISSUE TITLE
Данные фискализации

### ISSUE THREAD

**Issue by NekoiNemo** [shtrih-m/javapos_shtrih#93]
Добрый день.

Есть необходимость узнать текущие данные из фискального накопителя (агент, ИНН, etc). Для чтения регистрационных данных требуется номер фискализации, как можно получить текущий, или можно ли получить напрямую данные текущей фискализации?

**Comment by nyxiscoo1** [comment]
Добрый день.

Самый простой способ вычитать эти данные из таблицы фискального накопителя.

**Comment by NekoiNemo** [comment]
У метода readTable() иной набор параметров. Я знаю номера тэгов отвечающих за нужные значения, а не номера таблиц, рядов колонок

**Comment by nyxiscoo1** [comment]
```Java
FSReadExpDate cmd = new FSReadExpDate();
cmd.setSysPassword(printer.getSysPassword());
printer.executeCommand(cmd);
int regsCount = cmd.getRegistrationsCount();
```

Читать тэги можно так `byte[] tlv = printer.readFiscalizationTag(regsCount, tagNumber);`

**Comment by NekoiNemo** [comment]
Благодарю, получилось извлесь
